# Generated by Django 6.1.2 on 2026-10-07 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=24, unique=True, verbose_name='Discord ID')),
                ('username', models.CharField(max_length=40, verbose_name='Discord meno')),
                ('global_name', models.CharField(blank=True, max_length=64, verbose_name='zobrazované meno')),
                ('avatar', models.CharField(blank=True, max_length=64, verbose_name='avatar (hash)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrovaný')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='používateľ')),
            ],
            options={
                'verbose_name': 'hráč',
                'verbose_name_plural': 'hráči',
                'ordering': ['-created_at'],
            },
        ),
    ]
