# Generated by Django 6.1.2 on 2026-10-08 07:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('kingdom', '0003_kingdom_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governor_id', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{6,12}$', 'Governor ID má 6 až 12 číslic.')], verbose_name='Governor ID')),
                ('name', models.CharField(max_length=32, verbose_name='meno v hre')),
                ('kind', models.CharField(choices=[('main', 'Hlavný účet'), ('farm', 'Farma')], default='main', max_length=8, verbose_name='typ')),
                ('status', models.CharField(choices=[('pending', 'Čaká na schválenie'), ('approved', 'Schválený'), ('rejected', 'Zamietnutý')], default='pending', help_text='Pred schválením over v hre meno a Governor ID (profil governora, zoznam členov aliancie).', max_length=10, verbose_name='stav')),
                ('review_note', models.CharField(blank=True, help_text='Hráč ju uvidí pri governorovi na webe, napr. dôvod zamietnutia. Hromadné schválenie ju vymaže.', max_length=200, verbose_name='poznámka pre hráča')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='posúdené')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrovaný')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravený')),
                ('alliance', models.ForeignKey(blank=True, help_text='Prázdne = iná / žiadna.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governors', to='kingdom.alliance', verbose_name='aliancia')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governors', to='accounts.player', verbose_name='hráč')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posúdil')),
            ],
            options={
                'verbose_name': 'governor',
                'verbose_name_plural': 'governori',
                'ordering': [models.Case(models.When(status='pending', then=0), default=1), '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('governor_id',), name='governor_id_taken')],
            },
        ),
    ]
