# Generated by Django 6.1.2 on 2026-10-08 08:32

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_governor_player_ingame_name'),
        ('kingdom', '0004_player_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lang',
            field=models.CharField(choices=[('sk', 'slovenčina'), ('cs', 'čeština')], default='sk', help_text='Jazyk pripomienok – podľa verzie webu, na ktorej bol hráč naposledy.', max_length=2, verbose_name='jazyk'),
        ),
        migrations.AddField(
            model_name='player',
            name='remind_discord',
            field=models.BooleanField(default=True, help_text='Súkromná správa od bota pred eventmi, ktoré si vybral.', verbose_name='pripomienky na Discord'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='adresa push služby')),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorené')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='naposledy odoslané')),
                ('failures', models.PositiveSmallIntegerField(default=0, verbose_name='chyby za sebou')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.player', verbose_name='hráč')),
            ],
            options={
                'verbose_name': 'prehliadač s notifikáciami',
                'verbose_name_plural': 'prehliadače s notifikáciami',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offsets', models.JSONField(validators=[accounts.models.validate_offsets], verbose_name='minút pred začiatkom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravené')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='kingdom.kingdomevent', verbose_name='event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to='accounts.player', verbose_name='hráč')),
            ],
            options={
                'verbose_name': 'pripomienka hráča',
                'verbose_name_plural': 'pripomienky hráčov',
                'ordering': ['event', 'player'],
                'constraints': [models.UniqueConstraint(fields=('player', 'event'), name='one_reminder_per_player_event')],
            },
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.DateTimeField(verbose_name='termín eventu')),
                ('offset', models.PositiveIntegerField(verbose_name='minút pred začiatkom')),
                ('channel', models.CharField(choices=[('discord', 'Discord'), ('push', 'prehliadač')], max_length=8, verbose_name='kanál')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='odoslané')),
                ('ok', models.BooleanField(default=False, verbose_name='doručené')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='chyba')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kingdom.kingdomevent', verbose_name='event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.player', verbose_name='hráč')),
            ],
            options={
                'verbose_name': 'odoslaná pripomienka',
                'verbose_name_plural': 'odoslané pripomienky',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('player', 'event', 'occurrence', 'offset', 'channel'), name='one_personal_reminder_per_channel')],
            },
        ),
    ]
