# Generated by Django 6.1.2 on 2026-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentreminder',
            name='offset',
            field=models.IntegerField(verbose_name='minút pred začiatkom'),
        ),
    ]
