# Generated by Django 6.1.2 on 2026-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('commanderi', 'Commanderi (páry)'), ('vybava', 'Výbava'), ('eventy', 'Eventy')], max_length=16, verbose_name='kategória')),
                ('title_sk', models.CharField(max_length=160, verbose_name='nadpis (SK)')),
                ('title_cs', models.CharField(blank=True, help_text='Prázdne = na českej verzii sa zobrazí slovenský nadpis.', max_length=160, verbose_name='nadpis (CZ)')),
                ('slug', models.SlugField(help_text='Koniec adresy stránky – vyplní sa sám z nadpisu.', max_length=180, unique=True, verbose_name='adresa (URL)')),
                ('html_sk', models.TextField(help_text='Vlož HTML. Skripty, &lt;style&gt; bloky a nebezpečné atribúty sa pri uložení odstránia.', verbose_name='obsah HTML (SK)')),
                ('html_cs', models.TextField(blank=True, help_text='Prázdne = použije sa slovenský obsah.', verbose_name='obsah HTML (CZ)')),
                ('is_published', models.BooleanField(default=True, verbose_name='zverejnený')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menšie číslo = vyššie v zozname.', verbose_name='poradie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravené')),
            ],
            options={
                'verbose_name': 'návod',
                'verbose_name_plural': 'návody',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
