# Generated by Django 6.1.2 on 2026-10-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guides/%Y/%m/', verbose_name='obrázok')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='nahrané')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guides.guide', verbose_name='návod')),
            ],
            options={
                'verbose_name': 'obrázok',
                'verbose_name_plural': 'obrázky (nahraj a skopíruj kód do HTML)',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
