# Generated by Django 6.1.2 on 2026-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_guide_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('commanderi', 'Commanderi (páry)'), ('vybava', 'Výbava'), ('eventy', 'Eventy'), ('tipy', 'Tipy a triky')], max_length=16, verbose_name='kategória'),
        ),
    ]
