# Generated by Django 6.1.2 on 2026-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_tips_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='specialty',
            field=models.CharField(blank=True, choices=[('cavalry', 'Jazda'), ('infantry', 'Pechota'), ('archer', 'Lukostrelci'), ('leadership', 'Leadership'), ('garrison', 'Garrison'), ('conquering', 'Conquering (rally)'), ('peacekeeping', 'Peacekeeping (barbari)'), ('gathering', 'Gathering (zber)'), ('barbarian-fort', 'Barbarský fort (tipy)')], help_text='Herná ikona špecializácie commanderov pri návode v zozname, aby ho hráč rýchlo našiel. Prázdne = bez ikony. Automaticky aktualizovaným návodom ju nastavuje meta (backend/guides/meta).', max_length=16, verbose_name='špecializácia'),
        ),
    ]
