# Generated by Django 6.1.2 on 2026-10-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=8, verbose_name='tag')),
                ('name', models.CharField(max_length=64, verbose_name='názov')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='poradie')),
                ('is_active', models.BooleanField(default=True, verbose_name='zobraziť na webe')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravené')),
            ],
            options={
                'verbose_name': 'aliancia',
                'verbose_name_plural': 'aliancie',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nadpis')),
                ('message', models.TextField(blank=True, max_length=3500, verbose_name='text')),
                ('send_at', models.DateTimeField(help_text='Čas v Európe/Bratislave.', verbose_name='odoslať')),
                ('mention_role', models.BooleanField(default=True, help_text='Pingne Discord rolu nastavenú v DISCORD_EVENT_ROLE_ID.', verbose_name='označiť rolu')),
                ('status', models.CharField(choices=[('pending', 'Naplánovaná'), ('sent', 'Odoslaná'), ('failed', 'Chyba')], default='pending', max_length=8, verbose_name='stav')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='odoslaná')),
                ('error', models.TextField(blank=True, verbose_name='chyba')),
            ],
            options={
                'verbose_name': 'Discord notifikácia',
                'verbose_name_plural': 'Discord notifikácie',
                'ordering': ['-send_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('facebook', 'Facebook')], max_length=16, unique=True, verbose_name='platforma')),
                ('url', models.URLField(verbose_name='odkaz')),
                ('is_active', models.BooleanField(default=True, verbose_name='zobraziť na webe')),
            ],
            options={
                'verbose_name': 'odkaz',
                'verbose_name_plural': 'odkazy (Discord, Facebook)',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='meno v hre')),
                ('title_sk', models.CharField(help_text='napr. Vodca, Kancelár, R4', max_length=48, verbose_name='funkcia (SK)')),
                ('title_cs', models.CharField(help_text='např. Vůdce, Kancléř, R4', max_length=48, verbose_name='funkce (CZ)')),
                ('discord_id', models.CharField(blank=True, help_text='Číslo z Discordu (Developer Mode → pravý klik na profil → Copy User ID). Tlačidlo potom otvorí profil.', max_length=24, verbose_name='Discord User ID')),
                ('discord_username', models.CharField(blank=True, help_text='Bez ID tlačidlo skopíruje toto meno.', max_length=40, verbose_name='Discord meno')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='poradie')),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='kingdom.alliance', verbose_name='aliancia')),
            ],
            options={
                'verbose_name': 'člen vedenia',
                'verbose_name_plural': 'vedenie',
                'ordering': ['order', 'id'],
            },
        ),
    ]
