# Generated by Django 6.1.2 on 2026-10-07 18:55

import django.core.validators
import django.db.models.deletion
import kingdom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_seed_equipment_guides'),
        ('kingdom', '0002_seed_main_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='event_start',
            field=models.DateTimeField(blank=True, help_text='Discord ho každému ukáže v jeho časovom pásme aj s odpočtom.', null=True, verbose_name='začiatok eventu (nepovinné)'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='mention_role_id',
            field=models.CharField(blank=True, help_text='Prázdne = rola eventu, inak DISCORD_EVENT_ROLE_ID z .env.', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9]{5,24}$', 'Iba číslice (Developer Mode → pravý klik → Copy ID).')], verbose_name='ID roly (nepovinné)'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='occurrence_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termín eventu'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='offset_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='minút pred začiatkom'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='mention_role',
            field=models.BooleanField(default=True, help_text='Pingne rolu z poľa ID roly, inak DISCORD_EVENT_ROLE_ID.', verbose_name='označiť rolu'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Naplánovaná'), ('sent', 'Odoslaná'), ('failed', 'Chyba'), ('cancelled', 'Zrušená')], default='pending', max_length=16, verbose_name='stav'),
        ),
        migrations.CreateModel(
            name='KingdomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sk', models.CharField(help_text='Nadpis správy na Discorde.', max_length=80, verbose_name='názov (SK)')),
                ('name_cs', models.CharField(blank=True, help_text='Prázdne = použije sa slovenský názov.', max_length=80, verbose_name='název (CZ)')),
                ('message', models.TextField(blank=True, help_text='Môžeš použiť {name} = názov, {start} = dátum a čas začiatku, {relative} = „o 2 hodiny“, {end} = čas konca. Discord ich každému ukáže v jeho časovom pásme.', max_length=3000, verbose_name='text na Discord')),
                ('starts_at', models.DateTimeField(help_text='Čas v Európe/Bratislave. Ďalšie termíny sa počítajú od neho.', verbose_name='prvý začiatok')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='0 = bez konca.', verbose_name='trvanie (min)')),
                ('repeat_days', models.PositiveSmallIntegerField(default=0, help_text='0 = jednorazovo, 1 = denne, 7 = týždenne, 14 = každé 2 týždne.', verbose_name='opakovať každých (dní)')),
                ('until', models.DateField(blank=True, help_text='Prázdne = bez konca.', null=True, verbose_name='opakovať do (vrátane)')),
                ('time_basis', models.CharField(choices=[('utc', 'UTC – herný čas (u nás sa v lete/zime posunie o hodinu)'), ('local', 'Europe/Bratislava (u nás rovnaká hodina celý rok)')], default='utc', help_text='Herné eventy idú podľa UTC: u nás v lete o 2 h neskôr, v zime o 1 h.', max_length=8, verbose_name='čas sa drží v')),
                ('reminders', models.JSONField(blank=True, default=kingdom.models.default_reminders, help_text='Kedy pred začiatkom poslať správu na Discord.', validators=[kingdom.models.validate_reminders], verbose_name='pripomienky')),
                ('mention_role_id', models.CharField(blank=True, help_text='Discord Role ID len pre tento event. Prázdne = DISCORD_EVENT_ROLE_ID z .env.', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9]{5,24}$', 'Iba číslice (Developer Mode → pravý klik → Copy ID).')], verbose_name='ID roly (nepovinné)')),
                ('mention_role', models.BooleanField(default=True, verbose_name='označiť rolu')),
                ('notify_discord', models.BooleanField(default=True, verbose_name='posielať na Discord')),
                ('show_on_web', models.BooleanField(default=True, help_text='Pre kalendár eventov na webe.', verbose_name='zobraziť na webe')),
                ('is_active', models.BooleanField(default=True, help_text='Neaktívny event neposiela pripomienky.', verbose_name='aktívny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravené')),
                ('guide', models.ForeignKey(blank=True, help_text='Návod z kategórie Eventy (nepovinné).', limit_choices_to={'category': 'eventy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kingdom_events', to='guides.guide', verbose_name='návod')),
            ],
            options={
                'verbose_name': 'event kráľovstva',
                'verbose_name_plural': 'eventy kráľovstva',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kingdom.kingdomevent', verbose_name='event kráľovstva'),
        ),
        migrations.AddConstraint(
            model_name='eventnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'occurrence_start', 'offset_minutes'), name='one_reminder_per_occurrence'),
        ),
    ]
