# Generated by Django 6.1.2 on 2026-10-08 08:32

import kingdom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdom', '0003_kingdom_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdomevent',
            name='player_reminders',
            field=models.JSONField(blank=True, default=kingdom.models.default_player_reminders, help_text='Minúty pred začiatkom, ktoré hráčom ponúkneme na webe.', validators=[kingdom.models.validate_player_reminders], verbose_name='časy pre hráčov'),
        ),
        migrations.AlterField(
            model_name='kingdomevent',
            name='show_on_web',
            field=models.BooleanField(default=True, help_text='Hráči si ho môžu vybrať v pripomienkach na webe (Môj účet).', verbose_name='zobraziť na webe'),
        ),
    ]
