# Generated by Django 6.1.2 on 2026-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdom', '0004_player_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdomevent',
            name='irregular',
            field=models.BooleanField(default=False, help_text='Event bez pevného cyklu (napr. Silk Road, Shadow Legion). Pred každým konaním nastav „prvý začiatok“ na nový termín – hráčom, ktorí si ho vybrali, prídu pripomienky. Kým ďalší termín nie je, hráči ho vidia ako „ďalší termín oznámime“ a môžu si ho vybrať vopred.', verbose_name='nepravidelný'),
        ),
    ]
