# Generated by Django 6.1.2 on 2026-10-10 12:44

import kingdom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdom', '0011_show_on_web_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotification',
            name='offset_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='minút pred začiatkom'),
        ),
        migrations.AlterField(
            model_name='kingdomevent',
            name='reminders',
            field=models.JSONField(blank=True, default=kingdom.models.default_reminders, help_text='Kedy pred začiatkom poslať správu na Discord. Pri herných eventoch (00:00 UTC) „deň vopred o 18:00“.', validators=[kingdom.models.validate_reminders], verbose_name='pripomienky'),
        ),
    ]
