# Generated by Django 6.1.2 on 2026-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdom', '0014_karuak_ceremony'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='focus_cs',
            field=models.CharField(blank=True, help_text='např. Migrace, KvK, návody – prázdné = SK text', max_length=60, verbose_name='na čo sa obrátiť (CZ)'),
        ),
        migrations.AddField(
            model_name='officer',
            name='focus_sk',
            field=models.CharField(blank=True, help_text='napr. Migrácia, KvK, návody – prázdne = nezobrazí sa', max_length=60, verbose_name='na čo sa obrátiť (SK)'),
        ),
    ]
