"""Equipment guides (category Výbava). Kept up to date by the monthly meta update.

Write every text yourself in SK and CZ – facts from the sources listed in each guide, never copied prose.
"""

from .render import st, t

CATEGORY = 'vybava'
# year-month of the last check against current sources – shown as "Stav k októbru 2026" in every guide
VERIFIED = '2026-10'
NOTE = t(
    'Hodnoty sú pre predmet bez special talentu a bez prebudenia (Iconic).',
    'Hodnoty jsou pro předmět bez special talentu a bez probuzení (Iconic).',
)

GEAR = ['slot', 'item', 'stats', 'alt']

ROKSTATS = ('ROK Stats: Equipment database', 'https://app.rokstats.online/equipment')
RKG_EQUIP = ('Rise of Kingdoms Guides: Equipment Guide', 'https://riseofkingdomsguides.com/rise-of-kingdoms-equipment-guide/')
ROKGUIDE = ('rok.guide: Equipment Guide (archív)', 'https://web.archive.org/web/20240725162405/https://www.rok.guide/equipment-guide/')
PATCHES = ('Lilith: oficiálne patch notes', 'https://rok-club.lilith.com/')
LD_ACC = ('LDShop: Accessory Tier List (07/2026)', 'https://www.ldshop.gg/blog/rise-of-kingdoms/accessory-tier-list.html')

GUIDES = [
    {
        'slug': 'zaklady-vybavy-a-craftovania',
        'title': t('Základy výbavy a craftovania', 'Základy výbavy a craftění'),
        'blocks': [
            ('p', t(
                'Čo sa z výbavy naozaj ráta, čo craftovať najprv, ako funguje special talent a Iconic a koľko jednotlivé kusy stoja.',
                'Co se z výbavy opravdu počítá, co craftit nejdřív, jak funguje special talent a Iconic a kolik jednotlivé kusy stojí.',
            )),
            ('h2', t('Pravidlá', 'Pravidla')),
            ('ul', [
                t('<strong>Ráta sa len výbava primárneho commandera.</strong> Výbava sekundárneho nepridáva nič.',
                  '<strong>Počítá se jen výbava primárního commandera.</strong> Výbava sekundárního nepřidává nic.'),
                t('<strong>Výbava musí sedieť k jednotkám</strong>, ktoré commander vedie. Pre leadership a mix použi staty pre všetky jednotky (set Glorious Goddess).',
                  '<strong>Výbava musí sedět k jednotkám</strong>, které commander vede. Pro leadership a mix použij staty pro všechny jednotky (set Glorious Goddess).'),
                t('<strong>Najprv epická výbava</strong> na všetkých hlavných commanderov, až potom legendárna. Prechod z fialových na legendárne topánky pridá len asi 2 %.',
                  '<strong>Nejdřív epická výbava</strong> na všechny hlavní commandery, až potom legendární. Přechod z fialových na legendární boty přidá jen asi 2 %.'),
                t('<strong>Jedna armáda naplno</strong> skôr, než začneš druhú.',
                  '<strong>Jedna armáda naplno</strong> dřív, než začneš druhou.'),
                t('Pechota stavia na zdraví a obrane, lukostrelci na útoku a skill poškodení.',
                  'Pěchota staví na zdraví a obraně, lučištníci na útoku a skill poškození.'),
                t('Sety dávajú bonus za 2, 4 a 6 kusov. Prebudenie na vyšší Iconic tier set bonus nemení.',
                  'Sety dávají bonus za 2, 4 a 6 kusů. Probuzení na vyšší Iconic tier set bonus nemění.'),
                t('Najlepšie prilby a zbrane sú legendárne KvK kusy: Pride of the Khan, Helm of the Conqueror, Ancestral Mask of Night, Sacred Dominion, Hammer of the Sun and Moon a The Hydra’s Blast.',
                  'Nejlepší helmy a zbraně jsou legendární KvK kusy: Pride of the Khan, Helm of the Conqueror, Ancestral Mask of Night, Sacred Dominion, Hammer of the Sun and Moon a The Hydra’s Blast.'),
            ]),
            ('h2', t('Čo craftovať najprv', 'Co craftit nejdřív')),
            ('ul', [
                t('<strong>Pechota:</strong> Hope Cloak.', '<strong>Pěchota:</strong> Hope Cloak.'),
                t('<strong>Jazda:</strong> hruď a topánky zo setu Hellish Wasteland (bonus za 2 kusy).',
                  '<strong>Jízda:</strong> hruď a boty ze setu Hellish Wasteland (bonus za 2 kusy).'),
                t('<strong>Lukostrelci:</strong> hruď a rukavice zo setu Dragon’s Breath.',
                  '<strong>Lučištníci:</strong> hruď a rukavice ze setu Dragon’s Breath.'),
            ]),
            ('h2', t('Special talent', 'Special talent')),
            ('ul', [
                t('Pri každom craftovaní môže padnúť jeden z piatich talentov: Infantry, Cavalry, Archer, Integration alebo Leadership.',
                  'Při každém craftění může padnout jeden z pěti talentů: Infantry, Cavalry, Archer, Integration nebo Leadership.'),
                t('Ak má commander, ktorý predmet nosí, rovnaký talentový strom, všetky staty predmetu stúpnu o 30 % (z 3 % je asi 4 %).',
                  'Pokud má commander, který předmět nosí, stejný talentový strom, všechny staty předmětu stoupnou o 30 % (ze 3 % jsou asi 4 %).'),
                t('Refinement: s každým craftom sa plní lišta a pri 100 % je ďalší craft s talentom istý.',
                  'Refinement: s každým craftem se plní lišta a při 100 % je další craft s talentem jistý.'),
                t('Od júla 2025 vráti rozobratie legendárneho predmetu s talentom 100 % ceny craftu a 50 % ceny prebudenia.',
                  'Od července 2025 vrátí rozebrání legendárního předmětu s talentem 100 % ceny craftu a 50 % ceny probuzení.'),
            ]),
            ('h2', t('Iconic', 'Iconic')),
            ('ul', [
                t('Každý legendárny predmet okrem Trial of the Lost Kingdom a zberovej výbavy sa dá prebudiť na Iconic I–V.',
                  'Každý legendární předmět kromě Trial of the Lost Kingdom a sběrové výbavy jde probudit na Iconic I–V.'),
                t('Iconic I stojí Iconic Crystals a zlato, tiery II–V blueprinty, materiály a zlato. Refinement aj special talent zostanú.',
                  'Iconic I stojí Iconic Crystals a zlato, tiery II–V blueprinty, materiály a zlato. Refinement i special talent zůstanou.'),
                t('Iconic pridáva základný útok, obranu a zdravie jednotiek. Special talent tieto staty zvýši o 30 %.',
                  'Iconic přidává základní útok, obranu a zdraví jednotek. Special talent tyto staty zvýší o 30 %.'),
                t('Iconic V má špeciálne efekty (napr. Shattering Strike), ktoré od februára 2025 fungujú aj s combo a smite poškodením.',
                  'Iconic V má speciální efekty (např. Shattering Strike), které od února 2025 fungují i s combo a smite poškozením.'),
                t('Honing z januára 2026 platí len pre legendárne armamenty, nie pre výbavu.',
                  'Honing z ledna 2026 platí jen pro legendární armamenty, ne pro výbavu.'),
            ]),
            ('h2', t('Materiály a ceny', 'Materiály a ceny')),
            ('table', ['what', 'detail'], [
                {'what': t('Materiály', 'Materiály'),
                 'detail': t('Iron Ore, Leather, Ebony a Animal Bone (kosť hlavne na zberovú a EXP výbavu)',
                             'Iron Ore, Leather, Ebony a Animal Bone (kost hlavně na sběrovou a EXP výbavu)')},
                {'what': t('Kvalita', 'Kvalita'),
                 'detail': t('Normal → Advanced → Elite → Epic → Legendary, 4 rovnaké kusy = 1 kus vyššej kvality',
                             'Normal → Advanced → Elite → Epic → Legendary, 4 stejné kusy = 1 kus vyšší kvality')},
                {'what': t('Kováč', 'Kovář'),
                 'detail': t('10 materiálov za cyklus, front až 5 dávok. Nechaj ho bežať stále.',
                             '10 materiálů za cyklus, fronta až 5 dávek. Nech ho běžet pořád.')},
                {'what': t('Blueprint', 'Blueprint'), 'detail': t('30 fragmentov = 1 blueprint', '30 fragmentů = 1 blueprint')},
                {'what': t('Epická výbava', 'Epická výbava'), 'detail': t('5–6 mil. zlata, commander level 40', '5–6 mil. zlata, commander level 40')},
                {'what': t('Legendárny set', 'Legendární set'), 'detail': t('20 mil. zlata, level 45', '20 mil. zlata, level 45')},
                {'what': t('Ostatné legendárne', 'Ostatní legendární'), 'detail': t('15 mil. zlata', '15 mil. zlata')},
                {'what': t('KvK kusy', 'KvK kusy'), 'detail': t('30 mil. zlata, level 50', '30 mil. zlata, level 50')},
                {'what': t('Legendárne doplnky', 'Legendární doplňky'),
                 'detail': t('50 mil. zlata a po 40 legendárnych Iron Ore, Leather a Ebony',
                             '50 mil. zlata a po 40 legendárních Iron Ore, Leather a Ebony')},
            ]),
            ('sources', [ROKSTATS, PATCHES, RKG_EQUIP, ROKGUIDE]),
        ],
    },
    {
        'slug': 'vybava-pre-jazdu',
        'title': t('Výbava pre jazdu', 'Výbava pro jízdu'),
        'blocks': [
            ('p', t(
                'Najlepšia výbava pre jazdu na otvorené pole: KvK prilba a zbraň plus set Hellish Wasteland. Pre Arthura, Achilla aj Ivana IV.',
                'Nejlepší výbava pro jízdu na otevřené pole: KvK helma a zbraň plus set Hellish Wasteland. Pro Arthura, Achilla i Ivana IV.',
            )),
            ('note',),
            ('table', GEAR, [
                {'slot': 'helmet', 'item': 'Pride of the Khan (KvK)', 'stats': st(('def', 'cav', 15), ('hp', 'arch', 8)),
                 'alt': 'War Helm of the Hellish Wasteland'},
                {'slot': 'weapon', 'item': 'Sacred Dominion (KvK)', 'stats': st(('atk', 'cav', 25), ('def', 'arch', 5)),
                 'alt': t('epická Heart of the Saint, kým nemáš Sacred Dominion so special talentom',
                          'epická Heart of the Saint, dokud nemáš Sacred Dominion se special talentem')},
                {'slot': 'chest', 'item': 'Heavy Armor of the Hellish Wasteland', 'stats': st(('hp', 'cav', 11), ('atk', 'inf', 5)),
                 'alt': "Shadow Legion's Retribution"},
                {'slot': 'gloves', 'item': "Navar's Control", 'stats': st(('hp', 'cav', 8), ('def', 'inf', 5)),
                 'alt': 'Armband of the Hellish Wasteland'},
                {'slot': 'legs', 'item': 'Ash of the Dawn', 'stats': st(('hp', 'cav', 12), ('hp', 'inf', 5)),
                 'alt': 'Tassets of the Hellish Wasteland'},
                {'slot': 'boots', 'item': 'Boots of the Hellish Wasteland', 'stats': st(('hp', 'cav', 7.5), ('atk', 'arch', 3)),
                 'alt': 'Mountain Crushers'},
                {'slot': 'accessories', 'item': 'Horn of Fury + Ring of Doom',
                 'stats': t('rage a krátke dávky poškodenia', 'rage a krátké dávky poškození'), 'alt': ''},
            ]),
            ('h2', t('Set Hellish Wasteland', 'Set Hellish Wasteland')),
            ('ul', [
                t('2 kusy: +3 % zdravie jednotiek', '2 kusy: +3 % zdraví jednotek'),
                t('4 kusy: +3 % poškodenie protiútoku', '4 kusy: +3 % poškození protiútoku'),
                t('6 kusov: obrana jazdy (zdroje uvádzajú 3 % aj 5 %)', '6 kusů: obrana jízdy (zdroje uvádějí 3 % i 5 %)'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Prvý legendárny krok: hruď a topánky zo setu, spolu dajú bonus za 2 kusy.',
                  'První legendární krok: hruď a boty ze setu, spolu dají bonus za 2 kusy.'),
                t('Útočnejšia verzia: zbraň, nohavice aj topánky s útokom jazdy (Lance a Tassets of the Hellish Wasteland, Mountain Crushers).',
                  'Útočnější verze: zbraň, kalhoty i boty s útokem jízdy (Lance a Tassets of the Hellish Wasteland, Mountain Crushers).'),
            ]),
            ('sources', [ROKSTATS, ('AllClash: Achilles Builds', 'https://www.allclash.com/best-achilles-builds-talents-skill-order-pairing-equipment-in-rise-of-kingdoms/'), RKG_EQUIP]),
        ],
    },
    {
        'slug': 'vybava-pre-pechotu',
        'title': t('Výbava pre pechotu', 'Výbava pro pěchotu'),
        'blocks': [
            ('p', t(
                'Výbava pre pechotu na pole aj na garrison: obrana a zdravie, Hope Cloak a KvK kusy. Pre Sun Tzu Prime, Bai Qiho aj Tokugawu.',
                'Výbava pro pěchotu na pole i na garrison: obrana a zdraví, Hope Cloak a KvK kusy. Pro Sun Tzu Prime, Bai Qiho i Tokugawu.',
            )),
            ('note',),
            ('table', GEAR, [
                {'slot': 'helmet', 'item': 'Helm of the Conqueror (KvK)', 'stats': st(('def', 'inf', 15), ('hp', 'cav', 8)),
                 'alt': 'Gold Helm of the Eternal Empire'},
                {'slot': 'weapon', 'item': 'Hammer of the Sun and Moon (KvK)', 'stats': st(('atk', 'inf', 25), ('hp', 'arch', 5)),
                 'alt': 'Shield of the Eternal Empire'},
                {'slot': 'chest', 'item': 'Hope Cloak', 'stats': st(('def', 'inf', 12), ('def', 'cav', 5), ('def', 'arch', 5))},
                {'slot': 'gloves', 'item': 'Vambraces of the Eternal Empire', 'stats': st(('def', 'inf', 7.5), ('atk', 'cav', 3)),
                 'alt': 'Sacred Grips'},
                {'slot': 'legs', 'item': 'Eternal Night', 'stats': st(('def', 'inf', 12), ('def', 'arch', 5), ('def', 'cav', 5)),
                 'alt': t("epické Karuak's Humility (zdravie pechoty 8 %)", "epické Karuak's Humility (zdraví pěchoty 8 %)")},
                {'slot': 'boots', 'item': 'Sturdy Boots of the Eternal Empire', 'stats': st(('def', 'inf', 7.5), ('def', 'cav', 3)),
                 'alt': "Shio's Return"},
                {'slot': 'accessories', 'item': 'Horn of Fury + Ring of Doom',
                 'stats': t('rage a krátke dávky poškodenia', 'rage a krátké dávky poškození'), 'alt': ''},
            ]),
            ('h2', t('Set Eternal Empire', 'Set Eternal Empire')),
            ('ul', [
                t('2 kusy: +3 % obrana jednotiek', '2 kusy: +3 % obrana jednotek'),
                t('4 kusy: +10 % rýchlosť pochodu', '4 kusy: +10 % rychlost pochodu'),
                t('6 kusov: +5 % útok pechoty', '6 kusů: +5 % útok pěchoty'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Hope Cloak je prvý legendárny kus, ktorý sa pre pechotu oplatí craftnúť.',
                  'Hope Cloak je první legendární kus, který se pro pěchotu vyplatí craftit.'),
                t('Celý 6-kusový Eternal Empire je dobrý medzikrok, kým nemáš KvK prilbu a zbraň.',
                  'Celý 6kusový Eternal Empire je dobrý mezikrok, dokud nemáš KvK helmu a zbraň.'),
                t('Na nohavice sa zdroje delia medzi Eternal Night a epický Karuak’s Humility, ktorý má zdravie na úrovni legendárnych kusov.',
                  'Na kalhoty se zdroje dělí mezi Eternal Night a epický Karuak’s Humility, který má zdraví na úrovni legendárních kusů.'),
                t('<strong>Garrison</strong> používa rovnakú výbavu, len doplnky vymeň za Vengeance (+8 % poškodenie protiútoku) a Scolas’ Lucky Coin (šanca na štít pri zásahu).',
                  '<strong>Garrison</strong> používá stejnou výbavu, jen doplňky vyměň za Vengeance (+8 % poškození protiútoku) a Scolas’ Lucky Coin (šance na štít při zásahu).'),
            ]),
            ('sources', [ROKSTATS, ('AllClash: Scipio Prime Builds', 'https://www.allclash.com/best-scipio-prime-builds-talents-skill-order-pairing-equipment-in-rise-of-kingdoms/'), ('AllClash: Gorgo Builds', 'https://www.allclash.com/best-gorgo-builds-talents-skill-order-pairing-equipment-in-rise-of-kingdoms/'), RKG_EQUIP]),
        ],
    },
    {
        'slug': 'vybava-pre-lukostrelcov',
        'title': t('Výbava pre lukostrelcov', 'Výbava pro lučištníky'),
        'blocks': [
            ('p', t(
                'Výbava pre lukostrelcov: KvK prilba a zbraň plus set Dragon’s Breath so skill poškodením. Pre Qin Shi Huanga, Alp Arslana aj Hermanna.',
                'Výbava pro lučištníky: KvK helma a zbraň plus set Dragon’s Breath se skill poškozením. Pro Qin Shi Huanga, Alp Arslana i Hermanna.',
            )),
            ('note',),
            ('table', GEAR, [
                {'slot': 'helmet', 'item': 'Ancestral Mask of Night (KvK)', 'stats': st(('atk', 'arch', 15), ('atk', 'inf', 8)),
                 'alt': "Dragon's Breath Helm"},
                {'slot': 'weapon', 'item': "The Hydra's Blast (KvK)", 'stats': st(('def', 'arch', 25), ('def', 'cav', 5)),
                 'alt': "Dragon's Breath Bow"},
                {'slot': 'chest', 'item': "Dragon's Breath Plate", 'stats': st(('hp', 'arch', 11), ('def', 'cav', 5)),
                 'alt': 'The Milky Way'},
                {'slot': 'gloves', 'item': "Dragon's Breath Vambraces", 'stats': st(('atk', 'arch', 7.5), ('atk', 'inf', 3)),
                 'alt': "Ian's Choice"},
                {'slot': 'legs', 'item': "Dragon's Breath Tassets", 'stats': st(('atk', 'arch', 11), ('atk', 'cav', 5)),
                 'alt': 'Tassets of the War God'},
                {'slot': 'boots', 'item': "Dragon's Breath Boots", 'stats': st(('def', 'arch', 7.5), ('def', 'inf', 3)),
                 'alt': "Commander's Boots"},
                {'slot': 'accessories', 'item': 'Horn of Fury + Ring of Doom',
                 'stats': t('rage a krátke dávky poškodenia', 'rage a krátké dávky poškození'),
                 'alt': t('Pendant of Eternal Night pre Qin Shi Huanga (+5 % skill poškodenie)',
                          'Pendant of Eternal Night pro Qin Shi Huanga (+5 % skill poškození)')},
            ]),
            ('h2', t('Set Dragon’s Breath', 'Set Dragon’s Breath')),
            ('ul', [
                t('2 kusy: +3 % útok jednotiek', '2 kusy: +3 % útok jednotek'),
                t('4 kusy: +3 % skill poškodenie', '4 kusy: +3 % skill poškození'),
                t('6 kusov: +5 % zdravie lukostrelcov', '6 kusů: +5 % zdraví lučištníků'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Lukostrelecké zbrane dávajú obranu, nie útok.',
                  'Lučištnické zbraně dávají obranu, ne útok.'),
                t('S menším rozpočtom začni hruďou a rukavicami zo setu. Pri väčšom zbieraj 4 kusy kvôli skill poškodeniu.',
                  'S menším rozpočtem začni hrudí a rukavicemi ze setu. Při větším sbírej 4 kusy kvůli skill poškození.'),
            ]),
            ('sources', [ROKSTATS, ('AllClash: Alp Arslan Builds (05/2026)', 'https://www.allclash.com/best-alp-arslan-builds-talent-tree-skill-order-best-pairing-in-rise-of-kingdoms/'), RKG_EQUIP]),
        ],
    },
    {
        'slug': 'vybava-pre-leadership',
        'title': t('Výbava pre leadership a mix', 'Výbava pro leadership a mix'),
        'blocks': [
            ('p', t(
                'Leadership a miešané armády potrebujú staty pre všetky jednotky. Tie dáva set Glorious Goddess, napríklad pre Philipa II alebo Hectora.',
                'Leadership a smíšené armády potřebují staty pro všechny jednotky. Ty dává set Glorious Goddess, například pro Philipa II nebo Hectora.',
            )),
            ('note',),
            ('table', ['slot', 'item', 'stats'], [
                {'slot': 'weapon', 'item': 'Scepter of the Glorious Goddess',
                 'stats': t('útok jednotiek 15 %, rýchlosť pochodu pechoty 3 %', 'útok jednotek 15 %, rychlost pochodu pěchoty 3 %')},
                {'slot': 'helmet', 'item': 'Diadem of the Glorious Goddess',
                 'stats': t('útok jednotiek 8 %, rýchlosť pochodu jazdy 2 %', 'útok jednotek 8 %, rychlost pochodu jízdy 2 %')},
                {'slot': 'chest', 'item': t('Plate of the Glorious Goddess alebo Hope Cloak', 'Plate of the Glorious Goddess nebo Hope Cloak'),
                 'stats': st(('def', 'all', 8))},
                {'slot': 'gloves', 'item': 'Gauntlets of the Glorious Goddess', 'stats': st(('def', 'all', 6))},
                {'slot': 'legs', 'item': 'Chausses of the Glorious Goddess', 'stats': st(('hp', 'all', 8))},
                {'slot': 'boots', 'item': 'Greaves of the Glorious Goddess', 'stats': st(('hp', 'all', 6))},
            ]),
            ('h2', t('Set Glorious Goddess', 'Set Glorious Goddess')),
            ('ul', [
                t('2 kusy: +3 % obrana jednotiek', '2 kusy: +3 % obrana jednotek'),
                t('4 kusy: +3 % zníženie prijatého skill poškodenia', '4 kusy: +3 % snížení přijatého skill poškození'),
                t('6 kusov: +5 % zdravie jednotiek', '6 kusů: +5 % zdraví jednotek'),
                t('Každý kus stojí 20 mil. zlata a potrebuje commandera na leveli 45.',
                  'Každý kus stojí 20 mil. zlata a potřebuje commandera na levelu 45.'),
            ]),
            ('h2', t('Artefakty', 'Artefakty')),
            ('ul', [
                t('Emblem of Nike: +3,5 % útok všetkých jednotiek.', 'Emblem of Nike: +3,5 % útok všech jednotek.'),
                t('Pre jeden typ jednotiek: Lancer’s Banner (jazda), Berserker’s Brooch (pechota), Sniper’s Fletch (lukostrelci).',
                  'Pro jeden typ jednotek: Lancer’s Banner (jízda), Berserker’s Brooch (pěchota), Sniper’s Fletch (lučištníci).'),
                t('Od októbra 2025 majú Achilles a Hector exkluzívne artefakty, s ktorými ich skilly platia pre všetky typy jednotiek.',
                  'Od října 2025 mají Achilles a Hector exkluzivní artefakty, se kterými jejich skilly platí pro všechny typy jednotek.'),
            ]),
            ('sources', [ROKSTATS, ('AllClash: Hector Builds', 'https://www.allclash.com/best-hector-builds-talents-skill-order-pairing-equipment-in-rise-of-kingdoms/'), PATCHES]),
        ],
    },
    {
        'slug': 'najlepsie-doplnky',
        'title': t('Najlepšie doplnky (accessories)', 'Nejlepší doplňky (accessories)'),
        'blocks': [
            ('p', t(
                'Doplnky rozhodujú o rage a dávkach poškodenia. Prehľad podľa tierov a osvedčené kombinácie na pole, rally aj garrison.',
                'Doplňky rozhodují o rage a dávkách poškození. Přehled podle tierů a osvědčené kombinace na pole, rally i garrison.',
            )),
            ('note',),
            ('table', ['tier', 'accessory', 'effect'], [
                {'tier': 'S', 'accessory': 'Ring of Doom',
                 'effect': t('10 % šanca na +50 % poškodenia na 2 s, najviac raz za 5 s', '10 % šance na +50 % poškození na 2 s, nejvýš jednou za 5 s')},
                {'tier': 'S', 'accessory': 'Horn of Fury',
                 'effect': t('30 % šanca, že bežný útok obnoví 50 rage', '30 % šance, že běžný útok obnoví 50 rage')},
                {'tier': 'A', 'accessory': "Karuak's War Drums",
                 'effect': t('50 rage až dvom spojencom okolo, nie nositeľovi', '50 rage až dvěma spojencům kolem, ne nositeli')},
                {'tier': 'A', 'accessory': 'Greatest Glory', 'effect': t('+5 % poškodenie bežného útoku', '+5 % poškození běžného útoku')},
                {'tier': 'A', 'accessory': 'Pendant of Eternal Night', 'effect': t('+5 % skill poškodenie', '+5 % skill poškození')},
                {'tier': 'A', 'accessory': "Hero's Hilt", 'effect': t('posilňuje combo', 'posiluje combo')},
                {'tier': 'B', 'accessory': 'Vengeance', 'effect': t('+8 % poškodenie protiútoku', '+8 % poškození protiútoku')},
                {'tier': 'B', 'accessory': "Scolas' Lucky Coin",
                 'effect': t('10 % šanca na štít pri zásahu na 2 s, najviac raz za 5 s', '10 % šance na štít při zásahu na 2 s, nejvýš jednou za 5 s')},
                {'tier': 'B', 'accessory': "Concealed Dagger, Mora's Web, Seth's Call", 'effect': t('situačné', 'situační')},
                {'tier': 'C', 'accessory': 'Saddle of a Thousand Blessings', 'effect': t('posilňuje smite', 'posiluje smite')},
            ]),
            ('h2', t('Kombinácie', 'Kombinace')),
            ('ul', [
                t('<strong>Otvorené pole:</strong> Horn of Fury + Ring of Doom', '<strong>Otevřené pole:</strong> Horn of Fury + Ring of Doom'),
                t('<strong>Rally – vodca:</strong> Ring of Doom + Hero’s Hilt', '<strong>Rally – vůdce:</strong> Ring of Doom + Hero’s Hilt'),
                t('<strong>Rally – pripojení:</strong> Concealed Dagger + Mora’s Web', '<strong>Rally – připojení:</strong> Concealed Dagger + Mora’s Web'),
                t('<strong>Garrison:</strong> Vengeance + Scolas’ Lucky Coin', '<strong>Garrison:</strong> Vengeance + Scolas’ Lucky Coin'),
                t('<strong>Lacno:</strong> epické Silent Trial (bežné útoky berú cieľu 10 rage) + Delane’s Amulet (−5 % prijaté poškodenie protiútoku)',
                  '<strong>Levně:</strong> epické Silent Trial (běžné útoky berou cíli 10 rage) + Delane’s Amulet (−5 % přijaté poškození protiútoku)'),
            ]),
            ('p', t(
                'Tiery sú podľa LDShop (júl 2026). Omniarch (jún 2026) považuje Horn of Fury za najlepší doplnok. Epické doplnky sa dajú rozobrať s plnou náhradou materiálov.',
                'Tiery jsou podle LDShop (červenec 2026). Omniarch (červen 2026) považuje Horn of Fury za nejlepší doplněk. Epické doplňky jde rozebrat s plnou náhradou materiálů.',
            )),
            ('sources', [LD_ACC, ('Omniarch: Best Accessories 2026 (YouTube)', 'https://www.youtube.com/watch?v=XtAI7SO0t_I'), ROKSTATS]),
        ],
    },
    {
        'slug': 'vybava-pre-f2p',
        'title': t('Výbava pre F2P a začiatok hry', 'Výbava pro F2P a začátek hry'),
        'blocks': [
            ('p', t(
                'Lacná výbava bez legendárnych kusov, kým nemáš na KvK predmety. Epickú výbavu daj najprv všetkým hlavným commanderom.',
                'Levná výbava bez legendárních kusů, dokud nemáš na KvK předměty. Epickou výbavu dej nejdřív všem hlavním commanderům.',
            )),
            ('note',),
            ('table', ['troops', 'gear'], [
                {'troops': t('Jazda', 'Jízda'),
                 'gear': t('Windswept prilba, hruď, rukavice a topánky + Vanguard Halberd a Vanguard Greaves. Spolu asi +12,5 % útok, +9,5 % obrana, +10 % zdravie a +16 % rýchlosť pochodu.',
                           'Windswept helma, hruď, rukavice a boty + Vanguard Halberd a Vanguard Greaves. Dohromady asi +12,5 % útok, +9,5 % obrana, +10 % zdraví a +16 % rychlost pochodu.')},
                {'troops': t('Jazda – epické', 'Jízda – epické'),
                 'gear': t('Heart of the Saint, Abyssal Visage (útok jazdy 8 %), Dark Lord’s Blessing (obrana jazdy 8 %), Gladiator (zdravie jazdy 8 %), Cloud Racers (útok jazdy 5,5 %)',
                           'Heart of the Saint, Abyssal Visage (útok jízdy 8 %), Dark Lord’s Blessing (obrana jízdy 8 %), Gladiator (zdraví jízdy 8 %), Cloud Racers (útok jízdy 5,5 %)')},
                {'troops': t('Pechota', 'Pěchota'),
                 'gear': t('celý Windswept + Gatekeeper’s Shield (zdravie pechoty 8 %) + Karuak’s Humility',
                           'celý Windswept + Gatekeeper’s Shield (zdraví pěchoty 8 %) + Karuak’s Humility')},
                {'troops': t('Pechota – epické', 'Pěchota – epické'),
                 'gear': t('Sakura Fubuki (útok pechoty 13 %), Witch’s Lineage, Quinn’s Soul, Seth’s Brutality, Karuak’s Humility, The Scarlet Hounds',
                           'Sakura Fubuki (útok pěchoty 13 %), Witch’s Lineage, Quinn’s Soul, Seth’s Brutality, Karuak’s Humility, The Scarlet Hounds')},
                {'troops': t('Lukostrelci', 'Lučištníci'),
                 'gear': t('4 kusy epického setu Revival (2 kusy +3 % útok, 4 kusy +3 % obrana) a zbraň Golden Age (obrana lukostrelcov 13 %). Úplne zadarmo: Flame Treads (zdravie lukostrelcov 5,5 %).',
                           '4 kusy epického setu Revival (2 kusy +3 % útok, 4 kusy +3 % obrana) a zbraň Golden Age (obrana lučištníků 13 %). Úplně zdarma: Flame Treads (zdraví lučištníků 5,5 %).')},
                {'troops': t('Doplnky', 'Doplňky'),
                 'gear': t('Silent Trial + Delane’s Amulet. Ďalšie dobré epické: Call of the Loyal, Wind Scars, Ancient Stratagems.',
                           'Silent Trial + Delane’s Amulet. Další dobré epické: Call of the Loyal, Wind Scars, Ancient Stratagems.')},
            ]),
            ('h2', t('Na barbarov', 'Na barbary')),
            ('p', t(
                'Bonus k poškodeniu barbarom dávajú Savage Totem (+10 %) a epické Quinn’s Soul, Seth’s Brutality, Gladiator a Frost Treads (po +5 %).',
                'Bonus k poškození barbarům dávají Savage Totem (+10 %) a epické Quinn’s Soul, Seth’s Brutality, Gladiator a Frost Treads (po +5 %).',
            )),
            ('sources', [ROKGUIDE, RKG_EQUIP, LD_ACC]),
        ],
    },
]
