"""Event guides (category Eventy). Kept up to date by the monthly meta update.

Write every text yourself in SK and CZ – facts from the sources listed in each guide, never copied prose.
"""

from .render import t

CATEGORY = 'eventy'
# year-month of the last check against current sources – shown as "Stav k októbru 2026" in every guide
VERIFIED = '2026-10'
NOTE = t('Pravidlá a odmeny eventov sa môžu medzi kolami meniť, presné časy over v hre.',
         'Pravidla a odměny eventů se mohou mezi koly měnit, přesné časy ověř ve hře.')  # fmt: skip

APP_STORE = ('Lilith: poznámky k verziám (App Store, 2025–2026)', 'https://apps.apple.com/us/app/rise-of-kingdoms/id1354260888')
OMNIARCH_ROADMAP = ('Omniarch: roadmap (09/2026, YouTube)', 'https://www.youtube.com/watch?v=OFWCLSpF1nc')
AC_TIERS = ('AllClash: Commander Tier List (09/2026)', 'https://www.allclash.com/best-commanders-tier-list-in-rise-of-kingdoms-with-talents/')

GUIDES = [
    {
        'slug': 'kalendar-eventov',
        'title': t('Kalendár eventov a čo si šetriť', 'Kalendář eventů a co si šetřit'),
        'blocks': [
            ('p', t(
                'Ktoré eventy sa opakujú každý týždeň, mesiac alebo raz za KvK a na čo si šetriť speedupy, gemy a AP, aby si z nich vyťažil najviac.',
                'Které eventy se opakují každý týden, měsíc nebo jednou za KvK a na co si šetřit speedupy, gemy a AP, abys z nich vytěžil nejvíc.',
            )),
            ('note',),
            ('table', ['cadence', 'events'], [
                {'cadence': t('Denne a týždenne', 'Denně a týdně'),
                 'events': t('Sunset Canyon (5 pokusov denne, 7-dňová sezóna), Champions of Olympia (každý týždeň asi 2 dni)',
                             'Sunset Canyon (5 pokusů denně, 7denní sezóna), Champions of Olympia (každý týden asi 2 dny)')},
                {'cadence': t('Každé 2 týždne', 'Každé 2 týdny'),
                 'events': t('MGE a Ark of Osiris sa striedajú po týždňoch, Ceroli Crisis v druhej polovici cyklu MGE',
                             'MGE a Ark of Osiris se střídají po týdnech, Ceroli Crisis ve druhé polovině cyklu MGE')},
                {'cadence': t('Niekoľkokrát za mesiac', 'Několikrát za měsíc'),
                 'events': t('Golden Kingdom, Wheel of Fortune (zdroje uvádzajú každé 2 až 6 týždňov)',
                             'Golden Kingdom, Wheel of Fortune (zdroje uvádějí každé 2 až 6 týdnů)')},
                # MTG cadence confirmed in game by Gether (10/2026) – keep it even if older sources say 2–3 months
                {'cadence': t('Raz za mesiac', 'Jednou za měsíc'),
                 'events': t('Alliance Mobilization (7 dní), More Than Gems (2 dni) a sviatočná séria eventov',
                             'Alliance Mobilization (7 dní), More Than Gems (2 dny) a sváteční série eventů')},
                {'cadence': t('Každé 3–4 mesiace', 'Každé 3–4 měsíce'), 'events': 'Zenith of Power'},
                {'cadence': t('Asi každých 70 dní', 'Asi každých 70 dní'),
                 'events': t('noví commanderi na Wheel of Fortune a v MGE', 'noví commandeři na Wheel of Fortune a v MGE')},
                {'cadence': t('Každé KvK', 'Každé KvK'),
                 'events': t('príprava a Marauders pred KvK, Eve of the Crusade, Past Glory, honor body, výmena commanderov po KvK2',
                             'příprava a Marauders před KvK, Eve of the Crusade, Past Glory, honor body, výměna commanderů po KvK2')},
            ]),
            ('h2', t('Čo si šetriť', 'Co si šetřit')),
            ('ul', [
                t('<strong>Tréningové speedupy:</strong> tréningový deň a Final Sprint v MGE, tréning pred KvK. Rozšírenie tréningu nastav vopred.',
                  '<strong>Tréninkové speedupy:</strong> tréninkový den a Final Sprint v MGE, trénink před KvK. Rozšíření tréninku nastav předem.'),
                t('<strong>Liečebné a univerzálne speedupy:</strong> boje v KvK, približne 100 dní na armádu v KvK1 a 200+ v KvK2. Nemíňaj ich na lacnú silu.',
                  '<strong>Léčebné a univerzální speedupy:</strong> boje v KvK, přibližně 100 dní na armádu v KvK1 a 200+ v KvK2. Neutrácej je za levnou sílu.'),
                t('<strong>Gemy:</strong> 50 000 na celé More Than Gems (aspoň 7 000 na každý deň, do ktorého ideš) a zľavnené prvé točenia Wheel of Fortune len pre commanderov, ktorých plánuješ.',
                  '<strong>Gemy:</strong> 50 000 na celé More Than Gems (aspoň 7 000 na každý den, do kterého jdeš) a zlevněná první točení Wheel of Fortune jen pro commandery, které plánuješ.'),
                t('<strong>AP:</strong> barbarský deň v MGE, Marauders pred KvK, barbarské úlohy a Dark Fortress Raid.',
                  '<strong>AP:</strong> barbarský den v MGE, Marauders před KvK, barbarské úkoly a Dark Fortress Raid.'),
                t('<strong>Zlaté hlavy:</strong> na jeseň 2026 sa čaká viac nových commanderov, nesyp ich do niekoho, koho nebudeš používať.',
                  '<strong>Zlaté hlavy:</strong> na podzim 2026 se čeká víc nových commanderů, nesyp je do někoho, koho nebudeš používat.'),
                t('<strong>Formation choice chests a conversion stones:</strong> na november 2026 sa očakáva Delta Formation II.',
                  '<strong>Formation choice chests a conversion stones:</strong> na listopad 2026 se očekává Delta Formation II.'),
            ]),
            ('sources', [OMNIARCH_ROADMAP, ('Maffu: KvK2 guide (09/2026, YouTube)', 'https://www.youtube.com/watch?v=35GeDw8OeRo'), ('Commodore Boris: MGE full guide (YouTube)', 'https://www.youtube.com/watch?v=9JlR6sit8-0'), APP_STORE]),
        ],
    },
    {
        'slug': 'mightiest-governor-mge',
        'title': t('Mightiest Governor (MGE)', 'Mightiest Governor (MGE)'),
        'blocks': [
            ('p', t(
                'Individuálny rebríček v šiestich fázach s novým commanderom ako odmenou. Bodovanie, príprava a ako získať sošky aj bez top miesta.',
                'Individuální žebříček v šesti fázích s novým commanderem jako odměnou. Bodování, příprava a jak získat sošky i bez top místa.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Každé 2 týždne, vždy v opačnom týždni ako Ark of Osiris. Nový commander do MGE príde asi každých 70 dní a býva v ňom zhruba tri kolá.',
                  'Každé 2 týdny, vždy v opačném týdnu než Ark of Osiris. Nový commander do MGE přijde asi každých 70 dní a bývá v něm zhruba tři kola.'),
                t('Fázy: tréning, barbari, zber, sila, eliminácia nepriateľov a Final Sprint. Či fáza trvá deň alebo 48 hodín, over v hre, zdroje sa nezhodujú.',
                  'Fáze: trénink, barbaři, sběr, síla, eliminace nepřátel a Final Sprint. Zda fáze trvá den nebo 48 hodin, ověř ve hře, zdroje se neshodují.'),
                t('Odmenou sú sošky vybraného commandera, 10 sošiek ho odomkne.',
                  'Odměnou jsou sošky vybraného commandera, 10 sošek ho odemkne.'),
            ]),
            ('h2', t('Bodovanie', 'Bodování')),
            ('table', ['stage', 'points'], [
                {'stage': t('Tréning', 'Trénink'),
                 'points': t('T1 5, T2 10, T3 20, T4 40, T5 100 za jednotku. Vylepšenie jednotky dá len rozdiel medzi tiermi.',
                             'T1 5, T2 10, T3 20, T4 40, T5 100 za jednotku. Vylepšení jednotky dá jen rozdíl mezi tiery.')},
                {'stage': t('Barbari', 'Barbaři'),
                 'points': t('Viac za vyšší level. Ráta sa každý zúčastnený pochod, 5 pochodov na jedného barbara dá asi 5× viac.',
                             'Víc za vyšší level. Počítá se každý zúčastněný pochod, 5 pochodů na jednoho barbara dá asi 5× víc.')},
                {'stage': t('Zber', 'Sběr'),
                 'points': t('Za 100 surovín: jedlo a drevo 1, kameň 2, zlato 5. Body sa pripíšu až po návrate jednotiek do mesta.',
                             'Za 100 surovin: jídlo a dřevo 1, kámen 2, zlato 5. Body se připíšou až po návratu jednotek do města.')},
                {'stage': t('Sila', 'Síla'), 'points': t('2 body za každý bod sily', '2 body za každý bod síly')},
                {'stage': t('Eliminácia', 'Eliminace'),
                 'points': t('Body za zabité a ťažko zranené jednotky, vyšší tier dá viac.', 'Body za zabité a těžce zraněné jednotky, vyšší tier dá víc.')},
                {'stage': 'Final Sprint',
                 'points': t('Všetky činnosti spolu, približne za 80 % bežnej hodnoty.', 'Všechny činnosti dohromady, přibližně za 80 % běžné hodnoty.')},
            ]),
            ('h2', t('Odmeny za umiestnenie', 'Odměny za umístění')),
            ('table', ['rank', 'reward'], [
                {'rank': '1.', 'reward': t('180 sošiek', '180 sošek')},
                {'rank': '2.', 'reward': t('90 sošiek', '90 sošek')},
                {'rank': '3.', 'reward': t('60 sošiek', '60 sošek')},
                {'rank': '4.–6.', 'reward': t('50 / 40 / 30 sošiek', '50 / 40 / 30 sošek')},
                {'rank': '7.–10.', 'reward': t('20 sošiek', '20 sošek')},
                {'rank': '11.–15.', 'reward': t('10 sošiek', '10 sošek')},
                {'rank': '16.–25.', 'reward': t('5 sošiek', '5 sošek')},
                {'rank': '26.–35.', 'reward': t('3 sošky', '3 sošky')},
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Tréning bez speedupov: T5 tréning s rozšírením spusti približne (veľkosť rozšírenia ÷ 1 000 + 2) dní pred tréningovým dňom.',
                  'Trénink bez speedupů: T5 trénink s rozšířením spusť přibližně (velikost rozšíření ÷ 1 000 + 2) dní před tréninkovým dnem.'),
                t('Lacnejší trik: trénuj každý deň T2 (asi dvojnásobný výkon) a počas pushu ich vylepši na T5. Vyjde to lacnejšie, no vylepšené jednotky dajú menej bodov ako nové.',
                  'Levnější trik: trénuj každý den T2 (asi dvojnásobný výkon) a během pushe je vylepši na T5. Vyjde to levněji, ale vylepšené jednotky dají méně bodů než nové.'),
                t('Barbarský deň: reťaz barbarov s tankom a plošným commanderom. V KvK dostaneš navyše kryštály.',
                  'Barbarský den: řetěz barbarů s tankem a plošným commanderem. V KvK dostaneš navíc krystaly.'),
                t('Zber: pochody naložené zlatom nechaj na mape už počas barbarského dňa. Najlepší je aliančný zdroj zlata.',
                  'Sběr: pochody naložené zlatem nech na mapě už během barbarského dne. Nejlepší je alianční zdroj zlata.'),
                t('Deň sily: vyber hotový výskum a budovy, tréning a speedupy si nechaj na Final Sprint.',
                  'Den síly: vyber hotový výzkum a budovy, trénink a speedupy si nech na Final Sprint.'),
                t('Eliminácia: všetkých 5 pochodov na jeden cieľ, v KvK lov farmy nepriateľa. Vždy najprv pravidlá kráľovstva.',
                  'Eliminace: všech 5 pochodů na jeden cíl, v KvK lov farmy nepřítele. Vždy nejdřív pravidla království.'),
                t('Bez fixného miesta mier na 16.–35. miesto viac kôl za sebou. Dvakrát 16.–25. alebo raz 16.–25. a dvakrát 26.–35. dá 10–11 sošiek, teda odomknutie.',
                  'Bez fixního místa miř na 16.–35. místo víc kol za sebou. Dvakrát 16.–25. nebo jednou 16.–25. a dvakrát 26.–35. dá 10–11 sošek, tedy odemknutí.'),
            ]),
            ('h2', t('Fixné MGE', 'Fixní MGE')),
            ('p', t(
                'Kráľovstvá často určujú poradie vopred. Ostatní hráči majú strop bodov (napríklad 6 mil.) a fixné miesta sa skladajú nad ním s rezervou 0,5–2 mil. Prekročenie stropu je najčastejšia chyba.',
                'Království často určují pořadí předem. Ostatní hráči mají strop bodů (například 6 mil.) a fixní místa se skládají nad ním s rezervou 0,5–2 mil. Překročení stropu je nejčastější chyba.',
            )),
            ('sources', [('Commodore Boris: MGE full guide (YouTube)', 'https://www.youtube.com/watch?v=9JlR6sit8-0'), ('Commodore Boris: MGE planning (02/2025, YouTube)', 'https://www.youtube.com/watch?v=OdNUwldUsrs'), ('Pethris Prime: training (08/2025, YouTube)', 'https://www.youtube.com/watch?v=UaVCTPtG67w'), ('Heaven Guardian: Mightiest Governor (09/2026)', 'https://heaven-guardian.com/rise-of-kingdoms-win-mightiest-governor-event/'), OMNIARCH_ROADMAP]),
        ],
    },
    {
        'slug': 'priprava-na-kvk',
        'title': t('Príprava na KvK', 'Příprava na KvK'),
        'blocks': [
            ('p', t(
                'Kontrolný zoznam pred KvK1 a KvK2: koľko jednotiek, speedupov a surovín potrebuješ a na čo nezabudnúť.',
                'Kontrolní seznam před KvK1 a KvK2: kolik jednotek, speedupů a surovin potřebuješ a na co nezapomenout.',
            )),
            ('note',),
            ('table', ['what', 'kvk1', 'kvk2'], [
                {'what': t('Jednotky', 'Jednotky'),
                 'kvk1': t('asi 300 tisíc hlavného typu (naplní pochod s 50 % rozšírením)', 'asi 300 tisíc hlavního typu (naplní pochod s 50% rozšířením)'),
                 'kvk2': t('netrénuj zbytočne, low spender asi 400–500 tisíc', 'netrénuj zbytečně, low spender asi 400–500 tisíc')},
                {'what': t('Speedupy', 'Speedupy'),
                 'kvk1': t('asi 100 dní liečebných a univerzálnych na armádu', 'asi 100 dní léčebných a univerzálních na armádu'),
                 'kvk2': t('200+ dní', '200+ dní')},
                {'what': t('Suroviny', 'Suroviny'),
                 'kvk1': t('asi 1 mld. na zhruba 100 mil. kill points', 'asi 1 mld. na zhruba 100 mil. kill points'),
                 'kvk2': t('asi 2 mld. z každej potrebnej suroviny', 'asi 2 mld. z každé potřebné suroviny')},
                {'what': t('Budovy', 'Budovy'),
                 'kvk1': t('City Hall 25, Academy 24, nemocnice asi 340 tisíc pre jednu armádu', 'City Hall 25, Academy 24, nemocnice asi 340 tisíc pro jednu armádu'),
                 'kvk2': '—'},
                {'what': t('Commanderi', 'Commandeři'),
                 'kvk1': t('primárny na leveli 60, sekundárnym stačia skilly, epickí plne vyskillovaní', 'primární na levelu 60, sekundárním stačí skilly, epičtí plně vyskillovaní'),
                 'kvk2': t('jedna silná armáda, naplánuj výmenu commanderov', 'jedna silná armáda, naplánuj výměnu commanderů')},
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Postav jeden kompletný set výbavy pre hlavnú armádu.', 'Postav jeden kompletní set výbavy pro hlavní armádu.'),
                t('AP míňaj na Marauders, nie na barbarov v KvK (ak nejdeš po honor ranku).',
                  'AP utrácej za Marauders, ne za barbary v KvK (pokud nejdeš po honor ranku).'),
                t('V KvK2 sa pridaj k hlavnej bojovej aliancii, zbieraj honor, sleduj pretečenie nemocníc a drž sa v hlavnom zoskupení.',
                  'V KvK2 se přidej k hlavní bojové alianci, sbírej honor, sleduj přetečení nemocnic a drž se v hlavním uskupení.'),
                t('Po Lost Kingdom sezónach 1–3 nasleduje Season of Conquest. Nové príbehy 2025–26: Song of Troy, King of All Britain a Mighty Assembly.',
                  'Po Lost Kingdom sezónách 1–3 následuje Season of Conquest. Nové příběhy 2025–26: Song of Troy, King of All Britain a Mighty Assembly.'),
                t('Novinky 2026: honing armamentov, hlasovanie kráľov o Rest Mode, Camp Treaty a individuálne tituly za umiestnenie v sezóne.',
                  'Novinky 2026: honing armamentů, hlasování králů o Rest Mode, Camp Treaty a individuální tituly za umístění v sezóně.'),
            ]),
            ('sources', [('Maffu: KvK1 checklist (06/2026, YouTube)', 'https://www.youtube.com/watch?v=vPqcQZSgapM'), ('Maffu: KvK2 guide (09/2026, YouTube)', 'https://www.youtube.com/watch?v=35GeDw8OeRo'), APP_STORE]),
        ],
    },
    {
        'slug': 'ark-of-osiris',
        'title': t('Ark of Osiris', 'Ark of Osiris'),
        'blocks': [
            ('p', t(
                'Aliančné bojisko každé dva týždne. Bodovanie, úvodné ťahy, práca s Arkou a rozdiel medzi Golden a Silver Battlefield.',
                'Alianční bojiště každé dva týdny. Bodování, úvodní tahy, práce s Arkou a rozdíl mezi Golden a Silver Battlefield.',
            )),
            ('note',),
            ('h2', t('Formát', 'Formát')),
            ('ul', [
                t('<strong>Golden Battlefield:</strong> registruje aliancia, do 30 hráčov na stranu, 1 hodina, 5 koordinátorov, City Hall 16+.',
                  '<strong>Golden Battlefield:</strong> registruje aliance, až 30 hráčů na stranu, 1 hodina, 5 koordinátorů, City Hall 16+.'),
                t('<strong>Silver Battlefield:</strong> sólo alebo vlastný tím, súperi z iných kráľovstiev, 15 na stranu, 30 minút.',
                  '<strong>Silver Battlefield:</strong> sólo nebo vlastní tým, soupeři z jiných království, 15 na stranu, 30 minut.'),
                t('Povolení sú len commanderi zo sezóny tvojho kráľovstva, role sa dajú meniť do začiatku bitky. Golden Battlefield má od mája 2026 záznamy zápasov.',
                  'Povoleni jsou jen commandeři ze sezóny tvého království, role jde měnit do začátku bitvy. Golden Battlefield má od května 2026 záznamy zápasů.'),
            ]),
            ('h2', t('Bodovanie', 'Bodování')),
            ('table', ['objective', 'points'], [
                {'objective': 'Altar', 'points': t('750 za prvé obsadenie, potom 150 za minútu', '750 za první obsazení, potom 150 za minutu')},
                {'objective': 'Shrine', 'points': t('400 za prvé obsadenie, potom 80 za minútu', '400 za první obsazení, potom 80 za minutu')},
                {'objective': 'Outpost', 'points': t('30 za minútu', '30 za minutu')},
                {'objective': 'Ark', 'points': t('objaví sa v 15. minúte a potom každých 15 minút, jej doručenie je najväčší bodový zvrat',
                                                 'objeví se v 15. minutě a pak každých 15 minut, její doručení je největší bodový zvrat')},
                {'objective': 'Obelisk', 'points': t('obsadenie dá 8 teleportov, časom pribúdajú ďalšie', 'obsazení dá 8 teleportů, časem přibývají další')},
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Rozdeľte sa do 4 línií (dve dole, dve hore) a každý nech má písomne svoju oblasť a poradie teleportov.',
                  'Rozdělte se do 4 linií (dvě dole, dvě nahoře) a každý ať má písemně svou oblast a pořadí teleportů.'),
                t('Úvod: jazdecké rally na nepriateľské obelisky a outposty, rýchle pochody na vlastné obelisky a preteky o prvý oltár.',
                  'Úvod: jízdní rally na nepřátelské obelisky a outposty, rychlé pochody na vlastní obelisky a závod o první oltář.'),
                t('Poľné pochody vyčistia okolie skôr, ako dorazí rally. Garrisony drž plné a kto vedie rally alebo garrison, nechá si jeden pochod v zálohe.',
                  'Polní pochody vyčistí okolí dřív, než dorazí rally. Garrisony drž plné a kdo vede rally nebo garrison, nechá si jeden pochod v záloze.'),
                t('Pri Arke buď 2 minúty vopred, buffy zapni necelú minútu pred jej objavením. Nes ju jazdou do najbližšej vlastnej stavby, nikdy k nepriateľovi.',
                  'U Arky buď 2 minuty předem, buffy zapni necelou minutu před jejím objevením. Nes ji jízdou do nejbližší vlastní stavby, nikdy k nepříteli.'),
                t('Ustupujúce nepriateľské pochody nedobíjaj, nech strácajú čas.',
                  'Ustupující nepřátelské pochody nedobíjej, ať ztrácejí čas.'),
                t('Discord voice, aliančné skilly pripravené vopred a prázdne nemocnice pred zápasom.',
                  'Discord voice, alianční skilly připravené předem a prázdné nemocnice před zápasem.'),
                t('Commanderi: najsilnejšia poľná armáda tvojej sezóny, na Arku jazda.',
                  'Commandeři: nejsilnější polní armáda tvé sezóny, na Arku jízda.'),
            ]),
            ('h2', t('Osiris League', 'Osiris League')),
            ('p', t(
                'Elitný turnaj v Ark of Osiris. Aj diváci si prídu na svoje: stávky (prehraná stávka vráti 50 %), denné a týždenné úlohy a obchod, kde majú prednosť legendárne sošky.',
                'Elitní turnaj v Ark of Osiris. I diváci si přijdou na své: sázky (prohraná sázka vrátí 50 %), denní a týdenní úkoly a obchod, kde mají přednost legendární sošky.',
            )),
            ('sources', [('ROK with Cao: Ark of Osiris 2025 (07/2025, YouTube)', 'https://www.youtube.com/watch?v=xUMoX-OlLAg'), ('Rise of Kingdoms Guides: 1.0.90 patch notes', 'https://riseofkingdomsguides.com/rise-of-kingdoms-1-0-90-return-of-the-king-update/'), ('Rise of Kingdoms Guides: Osiris League betting', 'https://riseofkingdomsguides.com/rise-of-kingdoms-osiris-league-betting-guide/'), APP_STORE]),
        ],
    },
    {
        'slug': 'more-than-gems',
        'title': t('More Than Gems', 'More Than Gems'),
        'blocks': [
            ('p', t(
                'Dvojdňový event za míňanie gemov a hlavný zdroj zlatých hláv pre F2P. Koľko si nasporiť a za čo gemy minúť, aby to malo zmysel.',
                'Dvoudenní event za utrácení gemů a hlavní zdroj zlatých hlav pro F2P. Kolik si naspořit a za co gemy utratit, aby to mělo smysl.',
            )),
            ('note',),
            ('h2', t('Základy', 'Základy')),
            ('ul', [
                # cadence confirmed in game by Gether (10/2026) – keep it even if older sources say 2–3 months
                t('Prichádza raz za mesiac, občas s dlhším odstupom, keď sa prekrýva s inými eventami. Trvá 2 dni a každý deň má vlastné stupne odmien.',
                  'Přichází jednou za měsíc, občas s delším odstupem, když se překrývá s jinými eventy. Trvá 2 dny a každý den má vlastní stupně odměn.'),
                t('Zlaté hlavy dávajú stupne 7 000 a 25 000 gemov za deň. 25 000 za deň dalo asi 13 zlatých hláv, 50 000 za oba dni približne 26 plus speedupy a suroviny.',
                  'Zlaté hlavy dávají stupně 7 000 a 25 000 gemů za den. 25 000 za den dalo asi 13 zlatých hlav, 50 000 za oba dny přibližně 26 plus speedupy a suroviny.'),
                t('Rozhodni sa vopred: 25k + 25k, 25k + 7k alebo 7k + 7k. Nikdy neskonči tesne pod stupňom.',
                  'Rozhodni se předem: 25k + 25k, 25k + 7k nebo 7k + 7k. Nikdy neskonči těsně pod stupněm.'),
            ]),
            ('h2', t('Za čo gemy minúť', 'Za co gemy utratit')),
            ('ul', [
                t('Books of Covenant, ak máš City Hall pod 25.', 'Books of Covenant, pokud máš City Hall pod 25.'),
                t('VIP na zmysluplný level, napríklad VIP 14 dáva denné legendárne sošky.',
                  'VIP na smysluplný level, například VIP 14 dává denní legendární sošky.'),
                t('Legendárne materiály na výbavu (choice chests).', 'Legendární materiály na výbavu (choice chests).'),
                t('Zlaté hlavy, len ak commandera naozaj súrne potrebuješ, napríklad pred KvK.',
                  'Zlaté hlavy, jen pokud commandera opravdu naléhavě potřebuješ, například před KvK.'),
                t('24-hodinové speedupy, len ak ich máš odomknuté cez VIP. Suroviny nekupuj nikdy.',
                  '24hodinové speedupy, jen pokud je máš odemčené přes VIP. Suroviny nekupuj nikdy.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Ak práve beží Alliance Mobilization, splníš naraz aj jej úlohy na míňanie gemov.',
                  'Pokud právě běží Alliance Mobilization, splníš zároveň i její úkoly na utrácení gemů.'),
                t('Účty pod VIP 6 nemajú gemy na MTG zbytočne držať, rýchlejšie napredujú bežným míňaním.',
                  'Účty pod VIP 6 nemají gemy na MTG zbytečně držet, rychleji postupují běžným utrácením.'),
            ]),
            ('sources', [('Pethris Prime: More Than Gems (08/2025, YouTube)', 'https://www.youtube.com/watch?v=XAXhC-R-Pfs'), ('Rise of Kingdoms Guides: More Than Gems', 'https://riseofkingdomsguides.com/more-than-gems-event-guide/'), ('Sttuu: Alliance Mobilization rework (11/2025, YouTube)', 'https://www.youtube.com/watch?v=VV74DlACXl4')]),
        ],
    },
    {
        'slug': 'alliance-mobilization',
        'title': t('Alliance Mobilization', 'Alliance Mobilization'),
        'blocks': [
            ('p', t(
                'Mesačný aliančný event, ktorý od novembra 2025 dáva aj osobný obchod. Pre F2P jeden z najlepších zdrojov odmien.',
                'Měsíční alianční event, který od listopadu 2025 dává i osobní obchod. Pro F2P jeden z nejlepších zdrojů odměn.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Približne raz mesačne na 7 dní. Členovia plnia aliančné úlohy, body odomykajú stupne odmien a aliancie postupujú v ligách od Bronze vyššie.',
                  'Přibližně jednou měsíčně na 7 dní. Členové plní alianční úkoly, body odemykají stupně odměn a aliance postupují v ligách od Bronze výš.'),
                t('Lístky na úlohy: na začiatku asi 7, potom 1 zadarmo každý deň. Ten si treba vyzdvihnúť ručne, veľa hráčov naň zabúda. Ďalšie stoja gemy (300, 300, 600, 600, 1 000…).',
                  'Lístky na úkoly: na začátku asi 7, pak 1 zdarma každý den. Ten si je třeba vyzvednout ručně, hodně hráčů na něj zapomíná. Další stojí gemy (300, 300, 600, 600, 1 000…).'),
                t('Každá úloha dáva aj osobné mince do osobného obchodu: transmutation stones, legendárne materiály, zlaté hlavy.',
                  'Každý úkol dává i osobní mince do osobního obchodu: transmutation stones, legendární materiály, zlaté hlavy.'),
                t('Splnené úlohy sa po 24 hodinách odovzdajú samé.', 'Splněné úkoly se po 24 hodinách odevzdají samy.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Aliancia by mala dosiahnuť aspoň stupeň 12: legendárne formation choice chests a rozšírenia jednotiek o 50 tisíc inde F2P nezoženie.',
                  'Aliance by měla dosáhnout aspoň stupně 12: legendární formation choice chests a rozšíření jednotek o 50 tisíc jinde F2P neseženou.'),
                t('Zberové úlohy (asi 180 bodov) sú pre F2P najľahšie body.', 'Sběrové úkoly (asi 180 bodů) jsou pro F2P nejsnazší body.'),
                t('Úlohy na gemy spájaj s More Than Gems, tréningové s MGE alebo tréningom pred KvK.',
                  'Úkoly na gemy spojuj s More Than Gems, tréninkové s MGE nebo tréninkem před KvK.'),
                t('Na všetky osobné odmeny treba aspoň 800 osobných bodov.', 'Na všechny osobní odměny je potřeba aspoň 800 osobních bodů.'),
                t('R4: málo hodnotné modré úlohy rýchlo odstráňte.', 'R4: málo hodnotné modré úkoly rychle odstraňte.'),
                t('Legendárne formation choice chests si šetri, s Delta Formation II sa čaká event na legendárne armamenty.',
                  'Legendární formation choice chests si šetři, s Delta Formation II se čeká event na legendární armamenty.'),
            ]),
            ('sources', [('Sttuu: Alliance Mobilization rework (11/2025, YouTube)', 'https://www.youtube.com/watch?v=VV74DlACXl4'), ('Chisgule: Alliance Mobilization (11/2025, YouTube)', 'https://www.youtube.com/watch?v=1U94PtEv44k'), OMNIARCH_ROADMAP, APP_STORE]),
        ],
    },
    {
        'slug': 'wheel-of-fortune',
        'title': t('Wheel of Fortune', 'Wheel of Fortune'),
        'blocks': [
            ('p', t(
                'Trojdňové koleso za gemy s legendárnym commanderom. Kedy sa oplatí točiť, kde zastaviť a koľko to stojí.',
                'Třídenní kolo za gemy s legendárním commanderem. Kdy se vyplatí točit, kde zastavit a kolik to stojí.',
            )),
            ('note',),
            ('h2', t('Základy', 'Základy')),
            ('ul', [
                t('3 dni, jeden legendárny commander a míľniky na 10, 25, 45, 70 a 100 točení.',
                  '3 dny, jeden legendární commander a milníky na 10, 25, 45, 70 a 100 točení.'),
                t('Prvé točenie je zadarmo, ďalšie za polovičnú cenu (asi 400 gemov). 10 točení stojí podľa zdrojov 4 400 až 5 600 gemov, 100 točení zhruba 69 000–70 400.',
                  'První točení je zdarma, další za poloviční cenu (asi 400 gemů). 10 točení stojí podle zdrojů 4 400 až 5 600 gemů, 100 točení zhruba 69 000–70 400.'),
                t('V septembri 2026 Lilith ohlásila úpravy eventu bez podrobností, ceny preto over v hre.',
                  'V září 2026 Lilith ohlásila úpravy eventu bez podrobností, ceny proto ověř ve hře.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Toč, len ak commander posilní armádu, ktorú naozaj staviaš. Pomôžu návody o pároch commanderov.',
                  'Toč, jen pokud commander posílí armádu, kterou opravdu stavíš. Pomůžou návody o párech commanderů.'),
                t('Cieľový míľnik si vyber vopred a nikdy neskonči medzi míľnikmi.',
                  'Cílový milník si vyber předem a nikdy neskonči mezi milníky.'),
                t('Pre F2P má najlepší pomer zľavnené prvé točenie a míľnik 10 točení s 5 istými soškami.',
                  'Pro F2P má nejlepší poměr zlevněné první točení a milník 10 točení s 5 jistými soškami.'),
                t('Toč každý deň, aby si využil dennú zľavu.', 'Toč každý den, abys využil denní slevu.'),
            ]),
            ('sources', [('Heaven Guardian: Wheel of Fortune (08/2026)', 'https://heaven-guardian.com/rise-of-kingdoms-wheel-of-fortune-guide/'), ('Rise of Kingdoms Guides: Wheel of Fortune', 'https://riseofkingdomsguides.com/wheel-of-fortune-guide-in-rise-of-kingdoms/'), APP_STORE]),
        ],
    },
    {
        'slug': 'ceroli-crisis',
        'title': t('Ceroli Crisis', 'Ceroli Crisis'),
        'blocks': [
            ('p', t(
                'Kooperatívny boss event pre päť hráčov každé dva týždne. Zloženie tímu, commanderi a čo kúpiť za mince.',
                'Kooperativní boss event pro pět hráčů každé dva týdny. Složení týmu, commandeři a co koupit za mince.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Každé 2 týždne v druhej polovici cyklu MGE. Strieda sa 9 bossov, v jednom behu je ich 5.',
                  'Každé 2 týdny ve druhé polovině cyklu MGE. Střídá se 9 bossů, v jednom běhu je jich 5.'),
                t('Obťažnosť Normal a Legend (Legend asi od 50 mil. sily a od Season 2).',
                  'Obtížnost Normal a Legend (Legend asi od 50 mil. síly a od Season 2).'),
                t('Tímy po 5, sólo fronta alebo pozvánky aj naprieč kráľovstvami. Sila bossov aj odmeny sa riadia tvojou silou.',
                  'Týmy po 5, sólo fronta nebo pozvánky i napříč královstvími. Síla bossů i odměny se řídí tvou silou.'),
                t('Rátajú sa VIP, tituly, runy a téma mesta, vlastné buffy ani rozšírenia armády nie.',
                  'Počítají se VIP, tituly, runy a téma města, vlastní buffy ani rozšíření armády ne.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Pri Legend vždy čítaj modifikátory. Napríklad zabitie pomocníkov pod bossom nechá jedovaté kaluže, ktoré bossa liečia.',
                  'U Legend vždy čti modifikátory. Například zabití pomocníků pod bossem nechá jedovaté kaluže, které bosse léčí.'),
                t('V náhodnej skupine 2 tanky, 2 DPS a 1 liečiteľ, zohraté skupiny zvládnu aj 4–5 DPS.',
                  'V náhodné skupině 2 tanky, 2 DPS a 1 léčitel, sehrané skupiny zvládnou i 4–5 DPS.'),
                t('Všetci majú v slote 3 núdzové liečenie, tanky berú taunt.', 'Všichni mají ve slotu 3 nouzové léčení, tanky berou taunt.'),
                t('Shajar al-Durr ako sekundárny dá obrovskú výdrž.', 'Shajar al-Durr jako sekundární dá obrovskou výdrž.'),
                t('Na jedného bossa jednocieľoví nukeri (Arthur + Hector, Sun Tzu, William Wallace, Aethelflaed, Nevsky), na viac bossov plošné armády v strede.',
                  'Na jednoho bosse jednocíloví nukeři (Arthur + Hector, Sun Tzu, William Wallace, Aethelflaed, Nevsky), na víc bossů plošné armády uprostřed.'),
            ]),
            ('h2', t('Obchod', 'Obchod')),
            ('ul', [
                t('Plný Legend beh dá asi 13 300 mincí, nevyužité sa prenášajú do ďalšieho kola.',
                  'Plný Legend běh dá asi 13 300 mincí, nevyužité se přenášejí do dalšího kola.'),
                t('Poradie nákupu: materiály a lacný teleport, sošky Keiry pre novších hráčov, speedupy a nakoniec tri bojové buffy po 1 000 mincí.',
                  'Pořadí nákupu: materiály a levný teleport, sošky Keiry pro novější hráče, speedupy a nakonec tři bojové buffy po 1 000 mincí.'),
                t('Truhly bossov môžu dať aj fragmenty blueprintov.', 'Truhly bossů mohou dát i fragmenty blueprintů.'),
            ]),
            ('sources', [('Sttuu: Ceroli Crisis complete guide (03/2026, YouTube)', 'https://www.youtube.com/watch?v=J1wba64KXpQ')]),
        ],
    },
    {
        'slug': 'champions-of-olympia',
        'title': t('Champions of Olympia', 'Champions of Olympia'),
        'blocks': [
            ('p', t(
                'Týždenný 5v5 event, v ktorom sú všetci commanderi plne vyskillovaní. Rozhoduje zostava a súhra, nie peňaženka.',
                'Týdenní 5v5 event, ve kterém jsou všichni commandeři plně vyskillovaní. Rozhoduje sestava a souhra, ne peněženka.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Každý týždeň asi 2 dni, neranked aj ranked režim. Ranked má tri denné okná, sezóna trvá asi 2 mesiace.',
                  'Každý týden asi 2 dny, neranked i ranked režim. Ranked má tři denní okna, sezóna trvá asi 2 měsíce.'),
                t('Balanced mode: commanderi hrajú ako plne vyskillovaní a výbavu, armamenty aj talenty si volíš voľne.',
                  'Balanced mode: commandeři hrají jako plně vyskillovaní a výbavu, armamenty i talenty si volíš volně.'),
                t('Odmeny: asi 2 zlaté hlavy z neranked úloh, hviezdne truhly do 54 hviezd (prvé 3 výhry denne +1 hviezda) a gemy za umiestnenie na konci sezóny.',
                  'Odměny: asi 2 zlaté hlavy z neranked úkolů, hvězdné truhly do 54 hvězd (první 3 výhry denně +1 hvězda) a gemy za umístění na konci sezóny.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Priprav si presety a každému commanderovi daj talenty, výbavu aj armamenty. Prázdne presety sa v boji rozpadnú.',
                  'Připrav si presety a každému commanderovi dej talenty, výbavu i armamenty. Prázdné presety se v boji rozpadnou.'),
                t('Hraj na ciele. Na mape s vlajkami vyhráva držanie 3 vlajok, nenaháňaj nepriateľa do jeho spawnu.',
                  'Hraj na cíle. Na mapě s vlajkami vyhrává držení 3 vlajek, nenaháněj nepřítele do jeho spawnu.'),
                t('Ultimátky typov jednotiek: jazda (Iron Hoofs) na lukostrelcov, pechota (Boots on the Ground) na jazdu, lukostrelci (Range Mastery) na pechotu. Leadership (Shock and Awe) umlčí nepriateľov.',
                  'Ultimátky typů jednotek: jízda (Iron Hoofs) na lučištníky, pěchota (Boots on the Ground) na jízdu, lučištníci (Range Mastery) na pěchotu. Leadership (Shock and Awe) umlčí nepřátele.'),
                t('Nikdy nebuď AFK, dostaneš trest reputácie.', 'Nikdy nebuď AFK, dostaneš trest reputace.'),
            ]),
            ('h2', t('Zostavy (január 2026)', 'Sestavy (leden 2026)')),
            ('table', ['kind', 'lineup'], [
                {'kind': t('Jazda', 'Jízda'), 'lineup': 'Achilles + Gang Gamchan · Arthur + David IV / Hector'},
                {'kind': 'Leadership', 'lineup': 'Qin Shi Huang + Shajar al-Durr · Arthur + Achilles'},
                {'kind': t('Pechota', 'Pěchota'), 'lineup': 'Ragnar + Philip II · Scipio + Mehmed'},
                {'kind': t('Lukostrelci', 'Lučištníci'), 'lineup': 'Qin Shi Huang + Shajar al-Durr · Zhuge Liang + Hermann · Ashurbanipal + Yi Seong-Gye'},
            ]),
            ('sources', [('Sttuu: Champions of Olympia full guide (01/2026, YouTube)', 'https://www.youtube.com/watch?v=JTJ5_YXZJS4')]),
        ],
    },
    {
        'slug': 'sunset-canyon',
        'title': t('Sunset Canyon', 'Sunset Canyon'),
        'blocks': [
            ('p', t(
                'Asynchrónne súboje piatich armád s týždennými sezónami. Aktuálna meta stojí na leadership armáde Philip II + Shajar al-Durr.',
                'Asynchronní souboje pěti armád s týdenními sezónami. Aktuální meta stojí na leadership armádě Philip II + Shajar al-Durr.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Obranu nastavuješ bez znalosti útočníka, útočník tvoju zostavu vidí.',
                  'Obranu nastavuješ bez znalosti útočníka, útočník tvou sestavu vidí.'),
                t('Sezóna trvá 7 dní, 5 pokusov denne je zadarmo, ďalšie za lístky. Výhra pridáva rating, prehra uberá.',
                  'Sezóna trvá 7 dní, 5 pokusů denně je zdarma, další za lístky. Výhra přidává rating, prohra ubírá.'),
                t('Denné odmeny, odmeny za umiestnenie a mince do Canyon Shopu (od augusta 2026 aj fragmenty blueprintu Timeless Amber).',
                  'Denní odměny, odměny za umístění a mince do Canyon Shopu (od srpna 2026 i fragmenty blueprintu Timeless Amber).'),
            ]),
            ('h2', t('Meta 2026', 'Meta 2026')),
            ('ul', [
                t('<strong>Jadro:</strong> leadership armáda Philip II + Shajar al-Durr so silnými buffmi a liečením. AllClash radí Shajar medzi najlepších commanderov pre Canyon.',
                  '<strong>Jádro:</strong> leadership armáda Philip II + Shajar al-Durr se silnými buffy a léčením. AllClash řadí Shajar mezi nejlepší commandery pro Canyon.'),
                t('<strong>Poškodenie:</strong> lukostrelci Qin Shi Huang + Zhuge Liang a jazda vedená Achillom alebo Gang Gamchanom.',
                  '<strong>Poškození:</strong> lučištníci Qin Shi Huang + Zhuge Liang a jízda vedená Achillem nebo Gang Gamchanem.'),
                t('<strong>Bočná línia:</strong> Arthur + Hector. V obrane sa osvedčil Huo Qubing + Arthur.',
                  '<strong>Boční linie:</strong> Arthur + Hector. V obraně se osvědčil Huo Qubing + Arthur.'),
                t('<strong>Ďalšie možnosti:</strong> Sun Tzu + Constantine alebo dvojitý leadership (Trajan + Mulan, Trajan + Constantine).',
                  '<strong>Další možnosti:</strong> Sun Tzu + Constantine nebo dvojitý leadership (Trajan + Mulan, Trajan + Constantine).'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Pri 5 armádach 2–3 tanky vpredu a plošné poškodenie v strede.', 'U 5 armád 2–3 tanky vpředu a plošné poškození uprostřed.'),
                t('Otočenie zostavy (hore alebo dole) mení, koho zasiahnu plošné skilly. Proti konkrétnej obrane skús obe.',
                  'Otočení sestavy (nahoře nebo dole) mění, koho zasáhnou plošné skilly. Proti konkrétní obraně zkus obě.'),
                t('Keď vyprší čas, vyhráva strana s viac jednotkami. Odolná bočná armáda vie vyhrať záverečný súboj jeden na jedného.',
                  'Když vyprší čas, vyhrává strana s více jednotkami. Odolná boční armáda umí vyhrát závěrečný souboj jeden na jednoho.'),
                t('Extra lístky si nechaj na posledný deň sezóny.', 'Extra lístky si nech na poslední den sezóny.'),
                t('Staré rady o rovnakých T3 jednotkách a epických commanderoch už neplatia, rozhoduje výbava aj armamenty.',
                  'Staré rady o stejných T3 jednotkách a epických commanderech už neplatí, rozhoduje výbava i armamenty.'),
            ]),
            ('sources', [('Chisgule: Sunset Canyon meta review (06/2026, YouTube)', 'https://www.youtube.com/watch?v=kigArL0ftwQ'), AC_TIERS, APP_STORE]),
        ],
    },
    {
        'slug': 'golden-kingdom',
        'title': t('Golden Kingdom', 'Golden Kingdom'),
        'blocks': [
            ('p', t(
                'Sólo PvE dobrodružstvo po poschodiach s materiálmi a speedupmi za odmenu. Nestojí nič, tak ho nevynechávaj.',
                'Sólo PvE dobrodružství po patrech s materiály a speedupy za odměnu. Nestojí nic, tak ho nevynechávej.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Niekoľkokrát mesačne. Beh z roku 2025 mal 16 poschodí a finálneho bossa (staršie návody uvádzajú 20).',
                  'Několikrát měsíčně. Běh z roku 2025 měl 16 pater a finálního bosse (starší návody uvádějí 20).'),
                t('Ak nezoberieš truhly za 100 %, zopakovať sa to dá až v ďalšom behu. Beh trvá 20 až 40 minút.',
                  'Pokud nevezmeš truhly za 100 %, zopakovat to jde až v dalším běhu. Běh trvá 20 až 40 minut.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Poschodia 1–8 vyčisti celé kvôli požehnaniam a zlatu, potom hľadaj len náčelníka a chatu liečiteľa, ktorá je na každom poschodí.',
                  'Patra 1–8 vyčisti celá kvůli požehnáním a zlatu, pak hledej jen náčelníka a chatu léčitele, která je na každém patře.'),
                t('Najlepšie požehnania: Conqueror (pochod navyše) a Influential Leader (kapacita jednotiek).',
                  'Nejlepší požehnání: Conqueror (pochod navíc) a Influential Leader (kapacita jednotek).'),
                t('V obchode vždy kúp Bolt, Armor si nechaj na finálneho bossa.', 'V obchodě vždy kup Bolt, Armor si nech na finálního bosse.'),
                t('Relikvie nemíňaj na prvých náčelníkov.', 'Relikvie neutrácej za první náčelníky.'),
                t('Vpredu tanky (Trajan + Mulan, Trajan + Shajar al-Durr, mladšie účty Richard + Charles Martel), za nimi DPS a podporný commander ako 6. pochod.',
                  'Vpředu tanky (Trajan + Mulan, Trajan + Shajar al-Durr, mladší účty Richard + Charles Martel), za nimi DPS a podpůrný commander jako 6. pochod.'),
            ]),
            ('sources', [('ROK with Cao: Golden Kingdom (12/2025, YouTube)', 'https://www.youtube.com/watch?v=WUtdBXxlTwE'), ('Omniarch: Golden Kingdom (01/2025, YouTube)', 'https://www.youtube.com/watch?v=MEy_VR1lgc4')]),
        ],
    },
    {
        'slug': 'zenith-of-power',
        'title': t('Zenith of Power', 'Zenith of Power'),
        'blocks': [
            ('p', t(
                'Súťaž v náraste sily medzi zhruba ôsmimi kráľovstvami každé 3–4 mesiace. Hlavne pre veľké účty, ostatní ťažia z aliančných truhiel.',
                'Soutěž v nárůstu síly mezi zhruba osmi královstvími každé 3–4 měsíce. Hlavně pro velké účty, ostatní těží z aliančních truhel.',
            )),
            ('note',),
            ('h2', t('Ako funguje', 'Jak funguje')),
            ('ul', [
                t('Každé 3–4 mesiace, naposledy v decembri 2025, februári až marci 2026, júni 2026 a septembri 2026. Na december 2026 sa čaká téma pre jazdu.',
                  'Každé 3–4 měsíce, naposledy v prosinci 2025, únoru až březnu 2026, červnu 2026 a září 2026. Na prosinec 2026 se čeká téma pro jízdu.'),
                t('Za každých 5 mil. sily dostaneš odznak. 60 mil. sily (12 odznakov) kúpi hlavnú tému mesta bez ohľadu na umiestnenie, niektoré témy stáli 8 odznakov.',
                  'Za každých 5 mil. síly dostaneš odznak. 60 mil. síly (12 odznaků) koupí hlavní téma města bez ohledu na umístění, některá témata stála 8 odznaků.'),
                t('Top 10 získa tému natrvalo, top 3 aj animovaný avatar, nižšie miesta v top 100 dočasné verzie. Nevyužité odznaky sa menia na Faded badges na klasické témy.',
                  'Top 10 získá téma natrvalo, top 3 i animovaný avatar, nižší místa v top 100 dočasné verze. Nevyužité odznaky se mění na Faded badges na klasická témata.'),
            ]),
            ('h2', t('Tipy', 'Tipy')),
            ('ul', [
                t('Tlač len ak dosiahneš 60 mil. alebo si istý top 10. Inak ti po veľkom pushi ostane len 30-dňová téma.',
                  'Tlač jen pokud dosáhneš 60 mil. nebo si jsi jistý top 10. Jinak ti po velkém pushi zůstane jen 30denní téma.'),
                t('Maximalizuj rýchlosť tréningu: výskum, VIP, svätyne, kráľovský titul a buff, prípadne zmena civilizácie. Prvé zabitie guardiana denne dá počas Zenithu istú 15 % runu na tréning.',
                  'Maximalizuj rychlost tréninku: výzkum, VIP, svatyně, královský titul a buff, případně změna civilizace. První zabití guardiana denně dá během Zenithu jistou 15% runu na trénink.'),
                t('Počítaj vopred: zhruba 2 000 dní speedupov pri 95 % rýchlosti tréningu dá len asi 28 mil. sily.',
                  'Počítej předem: zhruba 2 000 dní speedupů při 95% rychlosti tréninku dá jen asi 28 mil. síly.'),
                t('Ak netlačíš, nezabudni na aliančné zlaté truhly, ktoré generujú tí, čo tlačia.',
                  'Pokud netlačíš, nezapomeň na alianční zlaté truhly, které generují ti, kdo tlačí.'),
            ]),
            ('sources', [('Sttuu: Should you go for Zenith? (08/2026, YouTube)', 'https://www.youtube.com/watch?v=z17HoiQReTM'), ('Maffu: Zenith changes (09/2025, YouTube)', 'https://www.youtube.com/watch?v=M9xH8CiyO3M'), APP_STORE]),
        ],
    },
    {
        'slug': 'nove-eventy-2025-2026',
        'title': t('Nové eventy 2025–2026', 'Nové eventy 2025–2026'),
        'blocks': [
            ('p', t(
                'Clash of Divine Isles, Radiant Rivalry, Dark Fortress Raid a Supreme Strife: čo sú zač a ako v nich bodovať.',
                'Clash of Divine Isles, Radiant Rivalry, Dark Fortress Raid a Supreme Strife: co jsou zač a jak v nich bodovat.',
            )),
            ('note',),
            ('h2', 'Clash of Divine Isles'),
            ('ul', [
                t('Zhruba týždeň: príprava (stavba strážcov sôch), invázia so striedaním bojových okien a oddychu, vyhodnotenie. 3–4 kráľovstvá z rovnakej sezóny, City Hall 21+.',
                  'Zhruba týden: příprava (stavba strážců soch), invaze se střídáním bojových oken a odpočinku, vyhodnocení. 3–4 království ze stejné sezóny, City Hall 21+.'),
                t('2 invázie denne po 10 minútach (porážaním nepriateľov až 15). V tíme do 5 hráčov bodujú členovia 120 %, kapitán 130 %, sólo hráč 100 %.',
                  '2 invaze denně po 10 minutách (porážením nepřátel až 15). V týmu do 5 hráčů bodují členové 120 %, kapitán 130 %, sólo hráč 100 %.'),
                t('Bránenie je neobmedzené, 15 minút na vstup a 30 minút cooldown. Buff sa riadi výbavou a armamentmi, runy, tituly ani kráľovské buffy neplatia.',
                  'Bránění je neomezené, 15 minut na vstup a 30 minut cooldown. Buff se řídí výbavou a armamenty, runy, tituly ani královské buffy neplatí.'),
                t('Od júna 2026 sa do bodov kráľovstva ráta len najlepšia denná invázia každého hráča.',
                  'Od června 2026 se do bodů království počítá jen nejlepší denní invaze každého hráče.'),
                t('Tipy: teleportuj namiesto pochodu, najprv zabi strážcov sochy, najviac bodov dajú sochy a elitné jednotky, brániť choď počas bojových okien.',
                  'Tipy: teleportuj místo pochodu, nejdřív zabij strážce sochy, nejvíc bodů dají sochy a elitní jednotky, bránit jdi během bojových oken.'),
            ]),
            ('h2', 'Radiant Rivalry'),
            ('p', t(
                'Dve susedné kráľovstvá plnia denné prípravné úlohy a víťaz dňa získa bod. Celkový víťaz sa teleportuje k porazenému a bojuje o jeho Radiant Spire, rozhoduje teda pravidelná denná účasť. Od júla 2026 beží v testovacích kráľovstvách, v septembri bol ohlásený pre ostatné.',
                'Dvě sousední království plní denní přípravné úkoly a vítěz dne získá bod. Celkový vítěz se teleportuje k poraženému a bojuje o jeho Radiant Spire, rozhoduje tedy pravidelná denní účast. Od července 2026 běží v testovacích královstvích, v září byl ohlášen pro ostatní.',
            )),
            ('h2', 'Dark Fortress Raid'),
            ('ul', [
                t('Aliančný event od septembra 2025. Členovia zabíjajú barbarov za raid mince a darujú ich na násobič poškodenia, nedarované mince sa menia na osobné body.',
                  'Alianční event od září 2025. Členové zabíjejí barbary za raid mince a darují je na násobič poškození, nedarované mince se mění na osobní body.'),
                t('Officeri naplánujú pevnosť a vyberú jej slabinu. Zvoľte typ jednotiek vašich najlepších rally.',
                  'Officeři naplánují pevnost a vyberou její slabinu. Zvolte typ jednotek vašich nejlepších rally.'),
                t('Až 8 rally naraz v 15-minútovom okne, každý hráč sa zúčastní len raz. Rally držte plné.',
                  'Až 8 rally najednou v 15minutovém okně, každý hráč se zúčastní jen jednou. Rally držte plné.'),
            ]),
            ('h2', 'Supreme Strife'),
            ('p', t(
                'Turnaj dočasných paktov hráčov z rôznych kráľovstiev v Season of Conquest (City Hall 25) z leta 2025: štyri soboty po 4 hodiny. Všetci majú maximálny crystal tech aj Past Glory a väčšina strát sa na konci obnoví. V roku 2026 zatiaľ nepotvrdený.',
                'Turnaj dočasných paktů hráčů z různých království v Season of Conquest (City Hall 25) z léta 2025: čtyři soboty po 4 hodinách. Všichni mají maximální crystal tech i Past Glory a většina ztrát se na konci obnoví. V roce 2026 zatím nepotvrzen.',
            )),
            ('sources', [('Chisgule: Clash of Divine Isles (04/2026, YouTube)', 'https://www.youtube.com/watch?v=ONA_DbDN2KA'), ('Shappy: Clash of Divine Isles (05/2026, YouTube)', 'https://www.youtube.com/watch?v=TRg-fGfUQ4o'), ('Pethris Prime: Dark Fortress Raid (08/2025, YouTube)', 'https://www.youtube.com/watch?v=kSgBXdi3F5w'), ('Chisgule: Supreme Strife (07/2025, YouTube)', 'https://www.youtube.com/watch?v=CL8_EeO-uF8'), APP_STORE]),
        ],
    },
]
